// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: realtime_event.proto

package realtimeevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRealtimeEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Event         []byte                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRealtimeEventReq) Reset() {
	*x = PushRealtimeEventReq{}
	mi := &file_realtime_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRealtimeEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRealtimeEventReq) ProtoMessage() {}

func (x *PushRealtimeEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRealtimeEventReq.ProtoReflect.Descriptor instead.
func (*PushRealtimeEventReq) Descriptor() ([]byte, []int) {
	return file_realtime_event_proto_rawDescGZIP(), []int{0}
}

func (x *PushRealtimeEventReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PushRealtimeEventReq) GetEvent() []byte {
	if x != nil {
		return x.Event
	}
	return nil
}

type PushRealtimeEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRealtimeEventResp) Reset() {
	*x = PushRealtimeEventResp{}
	mi := &file_realtime_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRealtimeEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRealtimeEventResp) ProtoMessage() {}

func (x *PushRealtimeEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRealtimeEventResp.ProtoReflect.Descriptor instead.
func (*PushRealtimeEventResp) Descriptor() ([]byte, []int) {
	return file_realtime_event_proto_rawDescGZIP(), []int{1}
}

var File_realtime_event_proto protoreflect.FileDescriptor

const file_realtime_event_proto_rawDesc = "" +
	"\n" +
	"\x14realtime_event.proto\x12\rrealtimeevent\"G\n" +
	"\x14PushRealtimeEventReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05event\x18\x02 \x01(\fR\x05event\"\x17\n" +
	"\x15PushRealtimeEventResp2p\n" +
	"\x14RealtimeEventService\x12X\n" +
	"\vPushToUsers\x12#.realtimeevent.PushRealtimeEventReq\x1a$.realtimeevent.PushRealtimeEventRespB-Z+github.com/maomeng/aim/pkg/pb/realtimeeventb\x06proto3"

var (
	file_realtime_event_proto_rawDescOnce sync.Once
	file_realtime_event_proto_rawDescData []byte
)

func file_realtime_event_proto_rawDescGZIP() []byte {
	file_realtime_event_proto_rawDescOnce.Do(func() {
		file_realtime_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_event_proto_rawDesc), len(file_realtime_event_proto_rawDesc)))
	})
	return file_realtime_event_proto_rawDescData
}

var file_realtime_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_realtime_event_proto_goTypes = []any{
	(*PushRealtimeEventReq)(nil),  // 0: realtimeevent.PushRealtimeEventReq
	(*PushRealtimeEventResp)(nil), // 1: realtimeevent.PushRealtimeEventResp
}
var file_realtime_event_proto_depIdxs = []int32{
	0, // 0: realtimeevent.RealtimeEventService.PushToUsers:input_type -> realtimeevent.PushRealtimeEventReq
	1, // 1: realtimeevent.RealtimeEventService.PushToUsers:output_type -> realtimeevent.PushRealtimeEventResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_realtime_event_proto_init() }
func file_realtime_event_proto_init() {
	if File_realtime_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_event_proto_rawDesc), len(file_realtime_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_event_proto_goTypes,
		DependencyIndexes: file_realtime_event_proto_depIdxs,
		MessageInfos:      file_realtime_event_proto_msgTypes,
	}.Build()
	File_realtime_event_proto = out.File
	file_realtime_event_proto_goTypes = nil
	file_realtime_event_proto_depIdxs = nil
}
