// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: bot/bot.proto

package bot

import (
	context "context"
	common "github.com/maomeng/aim/pkg/pb/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotService_StreamChat_FullMethodName              = "/bot.BotService/StreamChat"
	BotService_SummarizeConversation_FullMethodName   = "/bot.BotService/SummarizeConversation"
	BotService_GetConvSummaries_FullMethodName        = "/bot.BotService/GetConvSummaries"
	BotService_CreateTodo_FullMethodName              = "/bot.BotService/CreateTodo"
	BotService_UpdateTodo_FullMethodName              = "/bot.BotService/UpdateTodo"
	BotService_DeleteTodo_FullMethodName              = "/bot.BotService/DeleteTodo"
	BotService_GenerateReplyCandidates_FullMethodName = "/bot.BotService/GenerateReplyCandidates"
	BotService_TranslateMessage_FullMethodName        = "/bot.BotService/TranslateMessage"
	BotService_CreateBot_FullMethodName               = "/bot.BotService/CreateBot"
	BotService_UpdateBot_FullMethodName               = "/bot.BotService/UpdateBot"
	BotService_DeleteBot_FullMethodName               = "/bot.BotService/DeleteBot"
	BotService_GetBot_FullMethodName                  = "/bot.BotService/GetBot"
	BotService_ListBots_FullMethodName                = "/bot.BotService/ListBots"
	BotService_RotateSecret_FullMethodName            = "/bot.BotService/RotateSecret"
	BotService_HandleIncomingWebhook_FullMethodName   = "/bot.BotService/HandleIncomingWebhook"
	BotService_IssueBotToken_FullMethodName           = "/bot.BotService/IssueBotToken"
	BotService_ValidateBotToken_FullMethodName        = "/bot.BotService/ValidateBotToken"
	BotService_CreateMcpServer_FullMethodName         = "/bot.BotService/CreateMcpServer"
	BotService_UpdateMcpServer_FullMethodName         = "/bot.BotService/UpdateMcpServer"
	BotService_DeleteMcpServer_FullMethodName         = "/bot.BotService/DeleteMcpServer"
	BotService_GetMcpServer_FullMethodName            = "/bot.BotService/GetMcpServer"
	BotService_ListMcpServers_FullMethodName          = "/bot.BotService/ListMcpServers"
	BotService_AssignMcpToBot_FullMethodName          = "/bot.BotService/AssignMcpToBot"
	BotService_UnassignMcpFromBot_FullMethodName      = "/bot.BotService/UnassignMcpFromBot"
	BotService_ListBotMcpServers_FullMethodName       = "/bot.BotService/ListBotMcpServers"
	BotService_UpdateBotMcpServer_FullMethodName      = "/bot.BotService/UpdateBotMcpServer"
	BotService_DiscoverMcpTools_FullMethodName        = "/bot.BotService/DiscoverMcpTools"
	BotService_ListMcpTools_FullMethodName            = "/bot.BotService/ListMcpTools"
	BotService_BatchGetBots_FullMethodName            = "/bot.BotService/BatchGetBots"
	BotService_GetBotWebhookConfig_FullMethodName     = "/bot.BotService/GetBotWebhookConfig"
)

// BotServiceClient is the client API for BotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotServiceClient interface {
	StreamChat(ctx context.Context, in *StreamChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatResp], error)
	SummarizeConversation(ctx context.Context, in *SummarizeReq, opts ...grpc.CallOption) (*SummarizeResp, error)
	GetConvSummaries(ctx context.Context, in *GetConvSummariesReq, opts ...grpc.CallOption) (*GetConvSummariesResp, error)
	CreateTodo(ctx context.Context, in *CreateTodoReq, opts ...grpc.CallOption) (*TodoItem, error)
	UpdateTodo(ctx context.Context, in *UpdateTodoReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GenerateReplyCandidates(ctx context.Context, in *ReplyCandidatesReq, opts ...grpc.CallOption) (*ReplyCandidatesResp, error)
	TranslateMessage(ctx context.Context, in *TranslateMessageReq, opts ...grpc.CallOption) (*TranslateMessageResp, error)
	// Bot CRUD
	CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*Bot, error)
	UpdateBot(ctx context.Context, in *UpdateBotReq, opts ...grpc.CallOption) (*Bot, error)
	DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	GetBot(ctx context.Context, in *GetBotReq, opts ...grpc.CallOption) (*Bot, error)
	ListBots(ctx context.Context, in *ListBotsReq, opts ...grpc.CallOption) (*ListBotsResp, error)
	// Secret management
	RotateSecret(ctx context.Context, in *RotateSecretReq, opts ...grpc.CallOption) (*RotateSecretResp, error)
	// Webhook
	HandleIncomingWebhook(ctx context.Context, in *WebhookReq, opts ...grpc.CallOption) (*WebhookResp, error)
	// Bot Token
	IssueBotToken(ctx context.Context, in *IssueBotTokenReq, opts ...grpc.CallOption) (*IssueBotTokenResp, error)
	ValidateBotToken(ctx context.Context, in *ValidateBotTokenReq, opts ...grpc.CallOption) (*ValidateBotTokenResp, error)
	// Global MCP Server Management
	CreateMcpServer(ctx context.Context, in *CreateMcpServerReq, opts ...grpc.CallOption) (*McpServerInfo, error)
	UpdateMcpServer(ctx context.Context, in *UpdateMcpServerReq, opts ...grpc.CallOption) (*McpServerInfo, error)
	DeleteMcpServer(ctx context.Context, in *DeleteMcpServerReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	GetMcpServer(ctx context.Context, in *GetMcpServerReq, opts ...grpc.CallOption) (*McpServerInfo, error)
	ListMcpServers(ctx context.Context, in *ListMcpServersReq, opts ...grpc.CallOption) (*ListMcpServersResp, error)
	// Bot MCP Assignment
	AssignMcpToBot(ctx context.Context, in *AssignMcpToBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	UnassignMcpFromBot(ctx context.Context, in *UnassignMcpFromBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	ListBotMcpServers(ctx context.Context, in *ListBotMcpServersReq, opts ...grpc.CallOption) (*ListBotMcpServersResp, error)
	UpdateBotMcpServer(ctx context.Context, in *UpdateBotMcpServerReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// MCP Tool Discovery
	DiscoverMcpTools(ctx context.Context, in *DiscoverMcpToolsReq, opts ...grpc.CallOption) (*DiscoverMcpToolsResp, error)
	ListMcpTools(ctx context.Context, in *ListMcpToolsReq, opts ...grpc.CallOption) (*ListMcpToolsResp, error)
	// Read APIs for other services
	BatchGetBots(ctx context.Context, in *BatchGetBotsReq, opts ...grpc.CallOption) (*BatchGetBotsResp, error)
	GetBotWebhookConfig(ctx context.Context, in *GetBotWebhookConfigReq, opts ...grpc.CallOption) (*GetBotWebhookConfigResp, error)
}

type botServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotServiceClient(cc grpc.ClientConnInterface) BotServiceClient {
	return &botServiceClient{cc}
}

func (c *botServiceClient) StreamChat(ctx context.Context, in *StreamChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BotService_ServiceDesc.Streams[0], BotService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChatReq, StreamChatResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BotService_StreamChatClient = grpc.ServerStreamingClient[StreamChatResp]

func (c *botServiceClient) SummarizeConversation(ctx context.Context, in *SummarizeReq, opts ...grpc.CallOption) (*SummarizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeResp)
	err := c.cc.Invoke(ctx, BotService_SummarizeConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GetConvSummaries(ctx context.Context, in *GetConvSummariesReq, opts ...grpc.CallOption) (*GetConvSummariesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConvSummariesResp)
	err := c.cc.Invoke(ctx, BotService_GetConvSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) CreateTodo(ctx context.Context, in *CreateTodoReq, opts ...grpc.CallOption) (*TodoItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TodoItem)
	err := c.cc.Invoke(ctx, BotService_CreateTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) UpdateTodo(ctx context.Context, in *UpdateTodoReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BotService_UpdateTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BotService_DeleteTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GenerateReplyCandidates(ctx context.Context, in *ReplyCandidatesReq, opts ...grpc.CallOption) (*ReplyCandidatesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyCandidatesResp)
	err := c.cc.Invoke(ctx, BotService_GenerateReplyCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) TranslateMessage(ctx context.Context, in *TranslateMessageReq, opts ...grpc.CallOption) (*TranslateMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateMessageResp)
	err := c.cc.Invoke(ctx, BotService_TranslateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotService_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) UpdateBot(ctx context.Context, in *UpdateBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotService_UpdateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, BotService_DeleteBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GetBot(ctx context.Context, in *GetBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, BotService_GetBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ListBots(ctx context.Context, in *ListBotsReq, opts ...grpc.CallOption) (*ListBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotsResp)
	err := c.cc.Invoke(ctx, BotService_ListBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) RotateSecret(ctx context.Context, in *RotateSecretReq, opts ...grpc.CallOption) (*RotateSecretResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSecretResp)
	err := c.cc.Invoke(ctx, BotService_RotateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) HandleIncomingWebhook(ctx context.Context, in *WebhookReq, opts ...grpc.CallOption) (*WebhookResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookResp)
	err := c.cc.Invoke(ctx, BotService_HandleIncomingWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) IssueBotToken(ctx context.Context, in *IssueBotTokenReq, opts ...grpc.CallOption) (*IssueBotTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueBotTokenResp)
	err := c.cc.Invoke(ctx, BotService_IssueBotToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ValidateBotToken(ctx context.Context, in *ValidateBotTokenReq, opts ...grpc.CallOption) (*ValidateBotTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateBotTokenResp)
	err := c.cc.Invoke(ctx, BotService_ValidateBotToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) CreateMcpServer(ctx context.Context, in *CreateMcpServerReq, opts ...grpc.CallOption) (*McpServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServerInfo)
	err := c.cc.Invoke(ctx, BotService_CreateMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) UpdateMcpServer(ctx context.Context, in *UpdateMcpServerReq, opts ...grpc.CallOption) (*McpServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServerInfo)
	err := c.cc.Invoke(ctx, BotService_UpdateMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) DeleteMcpServer(ctx context.Context, in *DeleteMcpServerReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, BotService_DeleteMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GetMcpServer(ctx context.Context, in *GetMcpServerReq, opts ...grpc.CallOption) (*McpServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServerInfo)
	err := c.cc.Invoke(ctx, BotService_GetMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ListMcpServers(ctx context.Context, in *ListMcpServersReq, opts ...grpc.CallOption) (*ListMcpServersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpServersResp)
	err := c.cc.Invoke(ctx, BotService_ListMcpServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) AssignMcpToBot(ctx context.Context, in *AssignMcpToBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, BotService_AssignMcpToBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) UnassignMcpFromBot(ctx context.Context, in *UnassignMcpFromBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, BotService_UnassignMcpFromBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ListBotMcpServers(ctx context.Context, in *ListBotMcpServersReq, opts ...grpc.CallOption) (*ListBotMcpServersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotMcpServersResp)
	err := c.cc.Invoke(ctx, BotService_ListBotMcpServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) UpdateBotMcpServer(ctx context.Context, in *UpdateBotMcpServerReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, BotService_UpdateBotMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) DiscoverMcpTools(ctx context.Context, in *DiscoverMcpToolsReq, opts ...grpc.CallOption) (*DiscoverMcpToolsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverMcpToolsResp)
	err := c.cc.Invoke(ctx, BotService_DiscoverMcpTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) ListMcpTools(ctx context.Context, in *ListMcpToolsReq, opts ...grpc.CallOption) (*ListMcpToolsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpToolsResp)
	err := c.cc.Invoke(ctx, BotService_ListMcpTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) BatchGetBots(ctx context.Context, in *BatchGetBotsReq, opts ...grpc.CallOption) (*BatchGetBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetBotsResp)
	err := c.cc.Invoke(ctx, BotService_BatchGetBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botServiceClient) GetBotWebhookConfig(ctx context.Context, in *GetBotWebhookConfigReq, opts ...grpc.CallOption) (*GetBotWebhookConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBotWebhookConfigResp)
	err := c.cc.Invoke(ctx, BotService_GetBotWebhookConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServiceServer is the server API for BotService service.
// All implementations must embed UnimplementedBotServiceServer
// for forward compatibility.
type BotServiceServer interface {
	StreamChat(*StreamChatReq, grpc.ServerStreamingServer[StreamChatResp]) error
	SummarizeConversation(context.Context, *SummarizeReq) (*SummarizeResp, error)
	GetConvSummaries(context.Context, *GetConvSummariesReq) (*GetConvSummariesResp, error)
	CreateTodo(context.Context, *CreateTodoReq) (*TodoItem, error)
	UpdateTodo(context.Context, *UpdateTodoReq) (*emptypb.Empty, error)
	DeleteTodo(context.Context, *DeleteTodoReq) (*emptypb.Empty, error)
	GenerateReplyCandidates(context.Context, *ReplyCandidatesReq) (*ReplyCandidatesResp, error)
	TranslateMessage(context.Context, *TranslateMessageReq) (*TranslateMessageResp, error)
	// Bot CRUD
	CreateBot(context.Context, *CreateBotReq) (*Bot, error)
	UpdateBot(context.Context, *UpdateBotReq) (*Bot, error)
	DeleteBot(context.Context, *DeleteBotReq) (*common.BaseResponse, error)
	GetBot(context.Context, *GetBotReq) (*Bot, error)
	ListBots(context.Context, *ListBotsReq) (*ListBotsResp, error)
	// Secret management
	RotateSecret(context.Context, *RotateSecretReq) (*RotateSecretResp, error)
	// Webhook
	HandleIncomingWebhook(context.Context, *WebhookReq) (*WebhookResp, error)
	// Bot Token
	IssueBotToken(context.Context, *IssueBotTokenReq) (*IssueBotTokenResp, error)
	ValidateBotToken(context.Context, *ValidateBotTokenReq) (*ValidateBotTokenResp, error)
	// Global MCP Server Management
	CreateMcpServer(context.Context, *CreateMcpServerReq) (*McpServerInfo, error)
	UpdateMcpServer(context.Context, *UpdateMcpServerReq) (*McpServerInfo, error)
	DeleteMcpServer(context.Context, *DeleteMcpServerReq) (*common.BaseResponse, error)
	GetMcpServer(context.Context, *GetMcpServerReq) (*McpServerInfo, error)
	ListMcpServers(context.Context, *ListMcpServersReq) (*ListMcpServersResp, error)
	// Bot MCP Assignment
	AssignMcpToBot(context.Context, *AssignMcpToBotReq) (*common.BaseResponse, error)
	UnassignMcpFromBot(context.Context, *UnassignMcpFromBotReq) (*common.BaseResponse, error)
	ListBotMcpServers(context.Context, *ListBotMcpServersReq) (*ListBotMcpServersResp, error)
	UpdateBotMcpServer(context.Context, *UpdateBotMcpServerReq) (*common.BaseResponse, error)
	// MCP Tool Discovery
	DiscoverMcpTools(context.Context, *DiscoverMcpToolsReq) (*DiscoverMcpToolsResp, error)
	ListMcpTools(context.Context, *ListMcpToolsReq) (*ListMcpToolsResp, error)
	// Read APIs for other services
	BatchGetBots(context.Context, *BatchGetBotsReq) (*BatchGetBotsResp, error)
	GetBotWebhookConfig(context.Context, *GetBotWebhookConfigReq) (*GetBotWebhookConfigResp, error)
	mustEmbedUnimplementedBotServiceServer()
}

// UnimplementedBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotServiceServer struct{}

func (UnimplementedBotServiceServer) StreamChat(*StreamChatReq, grpc.ServerStreamingServer[StreamChatResp]) error {
	return status.Error(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedBotServiceServer) SummarizeConversation(context.Context, *SummarizeReq) (*SummarizeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeConversation not implemented")
}
func (UnimplementedBotServiceServer) GetConvSummaries(context.Context, *GetConvSummariesReq) (*GetConvSummariesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConvSummaries not implemented")
}
func (UnimplementedBotServiceServer) CreateTodo(context.Context, *CreateTodoReq) (*TodoItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedBotServiceServer) UpdateTodo(context.Context, *UpdateTodoReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTodo not implemented")
}
func (UnimplementedBotServiceServer) DeleteTodo(context.Context, *DeleteTodoReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTodo not implemented")
}
func (UnimplementedBotServiceServer) GenerateReplyCandidates(context.Context, *ReplyCandidatesReq) (*ReplyCandidatesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReplyCandidates not implemented")
}
func (UnimplementedBotServiceServer) TranslateMessage(context.Context, *TranslateMessageReq) (*TranslateMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TranslateMessage not implemented")
}
func (UnimplementedBotServiceServer) CreateBot(context.Context, *CreateBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedBotServiceServer) UpdateBot(context.Context, *UpdateBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBot not implemented")
}
func (UnimplementedBotServiceServer) DeleteBot(context.Context, *DeleteBotReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedBotServiceServer) GetBot(context.Context, *GetBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedBotServiceServer) ListBots(context.Context, *ListBotsReq) (*ListBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBots not implemented")
}
func (UnimplementedBotServiceServer) RotateSecret(context.Context, *RotateSecretReq) (*RotateSecretResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSecret not implemented")
}
func (UnimplementedBotServiceServer) HandleIncomingWebhook(context.Context, *WebhookReq) (*WebhookResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleIncomingWebhook not implemented")
}
func (UnimplementedBotServiceServer) IssueBotToken(context.Context, *IssueBotTokenReq) (*IssueBotTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueBotToken not implemented")
}
func (UnimplementedBotServiceServer) ValidateBotToken(context.Context, *ValidateBotTokenReq) (*ValidateBotTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateBotToken not implemented")
}
func (UnimplementedBotServiceServer) CreateMcpServer(context.Context, *CreateMcpServerReq) (*McpServerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMcpServer not implemented")
}
func (UnimplementedBotServiceServer) UpdateMcpServer(context.Context, *UpdateMcpServerReq) (*McpServerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMcpServer not implemented")
}
func (UnimplementedBotServiceServer) DeleteMcpServer(context.Context, *DeleteMcpServerReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMcpServer not implemented")
}
func (UnimplementedBotServiceServer) GetMcpServer(context.Context, *GetMcpServerReq) (*McpServerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMcpServer not implemented")
}
func (UnimplementedBotServiceServer) ListMcpServers(context.Context, *ListMcpServersReq) (*ListMcpServersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcpServers not implemented")
}
func (UnimplementedBotServiceServer) AssignMcpToBot(context.Context, *AssignMcpToBotReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignMcpToBot not implemented")
}
func (UnimplementedBotServiceServer) UnassignMcpFromBot(context.Context, *UnassignMcpFromBotReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignMcpFromBot not implemented")
}
func (UnimplementedBotServiceServer) ListBotMcpServers(context.Context, *ListBotMcpServersReq) (*ListBotMcpServersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBotMcpServers not implemented")
}
func (UnimplementedBotServiceServer) UpdateBotMcpServer(context.Context, *UpdateBotMcpServerReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBotMcpServer not implemented")
}
func (UnimplementedBotServiceServer) DiscoverMcpTools(context.Context, *DiscoverMcpToolsReq) (*DiscoverMcpToolsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverMcpTools not implemented")
}
func (UnimplementedBotServiceServer) ListMcpTools(context.Context, *ListMcpToolsReq) (*ListMcpToolsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcpTools not implemented")
}
func (UnimplementedBotServiceServer) BatchGetBots(context.Context, *BatchGetBotsReq) (*BatchGetBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetBots not implemented")
}
func (UnimplementedBotServiceServer) GetBotWebhookConfig(context.Context, *GetBotWebhookConfigReq) (*GetBotWebhookConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotWebhookConfig not implemented")
}
func (UnimplementedBotServiceServer) mustEmbedUnimplementedBotServiceServer() {}
func (UnimplementedBotServiceServer) testEmbeddedByValue()                    {}

// UnsafeBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotServiceServer will
// result in compilation errors.
type UnsafeBotServiceServer interface {
	mustEmbedUnimplementedBotServiceServer()
}

func RegisterBotServiceServer(s grpc.ServiceRegistrar, srv BotServiceServer) {
	// If the following call panics, it indicates UnimplementedBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotService_ServiceDesc, srv)
}

func _BotService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BotServiceServer).StreamChat(m, &grpc.GenericServerStream[StreamChatReq, StreamChatResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BotService_StreamChatServer = grpc.ServerStreamingServer[StreamChatResp]

func _BotService_SummarizeConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).SummarizeConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_SummarizeConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).SummarizeConversation(ctx, req.(*SummarizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GetConvSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConvSummariesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetConvSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetConvSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetConvSummaries(ctx, req.(*GetConvSummariesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_CreateTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).CreateTodo(ctx, req.(*CreateTodoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_UpdateTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).UpdateTodo(ctx, req.(*UpdateTodoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_DeleteTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).DeleteTodo(ctx, req.(*DeleteTodoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GenerateReplyCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyCandidatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GenerateReplyCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GenerateReplyCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GenerateReplyCandidates(ctx, req.(*ReplyCandidatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_TranslateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).TranslateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_TranslateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).TranslateMessage(ctx, req.(*TranslateMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).CreateBot(ctx, req.(*CreateBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_UpdateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).UpdateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_UpdateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).UpdateBot(ctx, req.(*UpdateBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).DeleteBot(ctx, req.(*DeleteBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetBot(ctx, req.(*GetBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ListBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ListBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ListBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ListBots(ctx, req.(*ListBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_RotateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).RotateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_RotateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).RotateSecret(ctx, req.(*RotateSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_HandleIncomingWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).HandleIncomingWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_HandleIncomingWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).HandleIncomingWebhook(ctx, req.(*WebhookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_IssueBotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueBotTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).IssueBotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_IssueBotToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).IssueBotToken(ctx, req.(*IssueBotTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ValidateBotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBotTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ValidateBotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ValidateBotToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ValidateBotToken(ctx, req.(*ValidateBotTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_CreateMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).CreateMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_CreateMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).CreateMcpServer(ctx, req.(*CreateMcpServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_UpdateMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMcpServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).UpdateMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_UpdateMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).UpdateMcpServer(ctx, req.(*UpdateMcpServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_DeleteMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMcpServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).DeleteMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_DeleteMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).DeleteMcpServer(ctx, req.(*DeleteMcpServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GetMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMcpServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetMcpServer(ctx, req.(*GetMcpServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ListMcpServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpServersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ListMcpServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ListMcpServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ListMcpServers(ctx, req.(*ListMcpServersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_AssignMcpToBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignMcpToBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).AssignMcpToBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_AssignMcpToBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).AssignMcpToBot(ctx, req.(*AssignMcpToBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_UnassignMcpFromBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignMcpFromBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).UnassignMcpFromBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_UnassignMcpFromBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).UnassignMcpFromBot(ctx, req.(*UnassignMcpFromBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ListBotMcpServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotMcpServersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ListBotMcpServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ListBotMcpServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ListBotMcpServers(ctx, req.(*ListBotMcpServersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_UpdateBotMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotMcpServerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).UpdateBotMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_UpdateBotMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).UpdateBotMcpServer(ctx, req.(*UpdateBotMcpServerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_DiscoverMcpTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverMcpToolsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).DiscoverMcpTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_DiscoverMcpTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).DiscoverMcpTools(ctx, req.(*DiscoverMcpToolsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_ListMcpTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpToolsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).ListMcpTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_ListMcpTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).ListMcpTools(ctx, req.(*ListMcpToolsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_BatchGetBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).BatchGetBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_BatchGetBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).BatchGetBots(ctx, req.(*BatchGetBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotService_GetBotWebhookConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotWebhookConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServiceServer).GetBotWebhookConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotService_GetBotWebhookConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServiceServer).GetBotWebhookConfig(ctx, req.(*GetBotWebhookConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BotService_ServiceDesc is the grpc.ServiceDesc for BotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bot.BotService",
	HandlerType: (*BotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SummarizeConversation",
			Handler:    _BotService_SummarizeConversation_Handler,
		},
		{
			MethodName: "GetConvSummaries",
			Handler:    _BotService_GetConvSummaries_Handler,
		},
		{
			MethodName: "CreateTodo",
			Handler:    _BotService_CreateTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _BotService_UpdateTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _BotService_DeleteTodo_Handler,
		},
		{
			MethodName: "GenerateReplyCandidates",
			Handler:    _BotService_GenerateReplyCandidates_Handler,
		},
		{
			MethodName: "TranslateMessage",
			Handler:    _BotService_TranslateMessage_Handler,
		},
		{
			MethodName: "CreateBot",
			Handler:    _BotService_CreateBot_Handler,
		},
		{
			MethodName: "UpdateBot",
			Handler:    _BotService_UpdateBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _BotService_DeleteBot_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _BotService_GetBot_Handler,
		},
		{
			MethodName: "ListBots",
			Handler:    _BotService_ListBots_Handler,
		},
		{
			MethodName: "RotateSecret",
			Handler:    _BotService_RotateSecret_Handler,
		},
		{
			MethodName: "HandleIncomingWebhook",
			Handler:    _BotService_HandleIncomingWebhook_Handler,
		},
		{
			MethodName: "IssueBotToken",
			Handler:    _BotService_IssueBotToken_Handler,
		},
		{
			MethodName: "ValidateBotToken",
			Handler:    _BotService_ValidateBotToken_Handler,
		},
		{
			MethodName: "CreateMcpServer",
			Handler:    _BotService_CreateMcpServer_Handler,
		},
		{
			MethodName: "UpdateMcpServer",
			Handler:    _BotService_UpdateMcpServer_Handler,
		},
		{
			MethodName: "DeleteMcpServer",
			Handler:    _BotService_DeleteMcpServer_Handler,
		},
		{
			MethodName: "GetMcpServer",
			Handler:    _BotService_GetMcpServer_Handler,
		},
		{
			MethodName: "ListMcpServers",
			Handler:    _BotService_ListMcpServers_Handler,
		},
		{
			MethodName: "AssignMcpToBot",
			Handler:    _BotService_AssignMcpToBot_Handler,
		},
		{
			MethodName: "UnassignMcpFromBot",
			Handler:    _BotService_UnassignMcpFromBot_Handler,
		},
		{
			MethodName: "ListBotMcpServers",
			Handler:    _BotService_ListBotMcpServers_Handler,
		},
		{
			MethodName: "UpdateBotMcpServer",
			Handler:    _BotService_UpdateBotMcpServer_Handler,
		},
		{
			MethodName: "DiscoverMcpTools",
			Handler:    _BotService_DiscoverMcpTools_Handler,
		},
		{
			MethodName: "ListMcpTools",
			Handler:    _BotService_ListMcpTools_Handler,
		},
		{
			MethodName: "BatchGetBots",
			Handler:    _BotService_BatchGetBots_Handler,
		},
		{
			MethodName: "GetBotWebhookConfig",
			Handler:    _BotService_GetBotWebhookConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _BotService_StreamChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bot/bot.proto",
}
