// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: audit-service/audit.proto

package audit

import (
	context "context"
	common "github.com/maomeng/aim/pkg/pb/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_RecordAudit_FullMethodName      = "/audit.AuditService/RecordAudit"
	AuditService_BatchRecordAudit_FullMethodName = "/audit.AuditService/BatchRecordAudit"
	AuditService_ListAudits_FullMethodName       = "/audit.AuditService/ListAudits"
	AuditService_GetAudit_FullMethodName         = "/audit.AuditService/GetAudit"
	AuditService_ExportAudits_FullMethodName     = "/audit.AuditService/ExportAudits"
	AuditService_ArchiveAudits_FullMethodName    = "/audit.AuditService/ArchiveAudits"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditService records and stores audit events to PostgreSQL.
// Other services call RecordAudit/BatchRecordAudit to persist audit trails.
// Query/export/archive are available for operational review.
// MVP: audit events are stored to DB; content review is async via Kafka consumer.
type AuditServiceClient interface {
	// record an audit event to DB (internal RPC, called by other services)
	RecordAudit(ctx context.Context, in *RecordAuditReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// batch record audit events to DB
	BatchRecordAudit(ctx context.Context, in *BatchRecordAuditReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// query audit logs from DB
	ListAudits(ctx context.Context, in *ListAuditsReq, opts ...grpc.CallOption) (*ListAuditsResp, error)
	// get single audit event from DB
	GetAudit(ctx context.Context, in *GetAuditReq, opts ...grpc.CallOption) (*GetAuditResp, error)
	// export audit logs
	ExportAudits(ctx context.Context, in *ExportAuditsReq, opts ...grpc.CallOption) (*ExportAuditsResp, error)
	// archive / cleanup old audit logs
	ArchiveAudits(ctx context.Context, in *ArchiveAuditsReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) RecordAudit(ctx context.Context, in *RecordAuditReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, AuditService_RecordAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) BatchRecordAudit(ctx context.Context, in *BatchRecordAuditReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, AuditService_BatchRecordAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListAudits(ctx context.Context, in *ListAuditsReq, opts ...grpc.CallOption) (*ListAuditsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditsResp)
	err := c.cc.Invoke(ctx, AuditService_ListAudits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetAudit(ctx context.Context, in *GetAuditReq, opts ...grpc.CallOption) (*GetAuditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditResp)
	err := c.cc.Invoke(ctx, AuditService_GetAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ExportAudits(ctx context.Context, in *ExportAuditsReq, opts ...grpc.CallOption) (*ExportAuditsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportAuditsResp)
	err := c.cc.Invoke(ctx, AuditService_ExportAudits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ArchiveAudits(ctx context.Context, in *ArchiveAuditsReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, AuditService_ArchiveAudits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
//
// AuditService records and stores audit events to PostgreSQL.
// Other services call RecordAudit/BatchRecordAudit to persist audit trails.
// Query/export/archive are available for operational review.
// MVP: audit events are stored to DB; content review is async via Kafka consumer.
type AuditServiceServer interface {
	// record an audit event to DB (internal RPC, called by other services)
	RecordAudit(context.Context, *RecordAuditReq) (*common.BaseResponse, error)
	// batch record audit events to DB
	BatchRecordAudit(context.Context, *BatchRecordAuditReq) (*common.BaseResponse, error)
	// query audit logs from DB
	ListAudits(context.Context, *ListAuditsReq) (*ListAuditsResp, error)
	// get single audit event from DB
	GetAudit(context.Context, *GetAuditReq) (*GetAuditResp, error)
	// export audit logs
	ExportAudits(context.Context, *ExportAuditsReq) (*ExportAuditsResp, error)
	// archive / cleanup old audit logs
	ArchiveAudits(context.Context, *ArchiveAuditsReq) (*common.BaseResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) RecordAudit(context.Context, *RecordAuditReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAudit not implemented")
}
func (UnimplementedAuditServiceServer) BatchRecordAudit(context.Context, *BatchRecordAuditReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchRecordAudit not implemented")
}
func (UnimplementedAuditServiceServer) ListAudits(context.Context, *ListAuditsReq) (*ListAuditsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudits not implemented")
}
func (UnimplementedAuditServiceServer) GetAudit(context.Context, *GetAuditReq) (*GetAuditResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudit not implemented")
}
func (UnimplementedAuditServiceServer) ExportAudits(context.Context, *ExportAuditsReq) (*ExportAuditsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportAudits not implemented")
}
func (UnimplementedAuditServiceServer) ArchiveAudits(context.Context, *ArchiveAuditsReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveAudits not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_RecordAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAuditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).RecordAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_RecordAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).RecordAudit(ctx, req.(*RecordAuditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_BatchRecordAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRecordAuditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).BatchRecordAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_BatchRecordAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).BatchRecordAudit(ctx, req.(*BatchRecordAuditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListAudits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListAudits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListAudits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListAudits(ctx, req.(*ListAuditsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetAudit(ctx, req.(*GetAuditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ExportAudits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportAuditsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ExportAudits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ExportAudits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ExportAudits(ctx, req.(*ExportAuditsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ArchiveAudits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveAuditsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ArchiveAudits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ArchiveAudits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ArchiveAudits(ctx, req.(*ArchiveAuditsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordAudit",
			Handler:    _AuditService_RecordAudit_Handler,
		},
		{
			MethodName: "BatchRecordAudit",
			Handler:    _AuditService_BatchRecordAudit_Handler,
		},
		{
			MethodName: "ListAudits",
			Handler:    _AuditService_ListAudits_Handler,
		},
		{
			MethodName: "GetAudit",
			Handler:    _AuditService_GetAudit_Handler,
		},
		{
			MethodName: "ExportAudits",
			Handler:    _AuditService_ExportAudits_Handler,
		},
		{
			MethodName: "ArchiveAudits",
			Handler:    _AuditService_ArchiveAudits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit-service/audit.proto",
}
