// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package server

import (
	"context"

	"github.com/maomeng/aim/app/message-service/pb/message"
	"github.com/maomeng/aim/app/message-service/internal/logic"
	"github.com/maomeng/aim/app/message-service/internal/svc"
	"github.com/maomeng/aim/pkg/pb/common"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

// ========== Core ==========
func (s *MessageServiceServer) SendMessage(ctx context.Context, in *message.SendMessageReq) (*message.SendMessageResp, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *MessageServiceServer) RecallMessage(ctx context.Context, in *message.RecallMessageReq) (*common.BaseResponse, error) {
	l := logic.NewRecallMessageLogic(ctx, s.svcCtx)
	return l.RecallMessage(in)
}

func (s *MessageServiceServer) EditMessage(ctx context.Context, in *message.EditMessageReq) (*common.BaseResponse, error) {
	l := logic.NewEditMessageLogic(ctx, s.svcCtx)
	return l.EditMessage(in)
}

func (s *MessageServiceServer) DeleteMessage(ctx context.Context, in *message.DeleteMessageReq) (*common.BaseResponse, error) {
	l := logic.NewDeleteMessageLogic(ctx, s.svcCtx)
	return l.DeleteMessage(in)
}

// ========== Query ==========
func (s *MessageServiceServer) GetMessages(ctx context.Context, in *message.GetMessagesReq) (*message.GetMessagesResp, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

func (s *MessageServiceServer) SyncMessages(ctx context.Context, in *message.SyncMessagesReq) (*message.SyncMessagesResp, error) {
	l := logic.NewSyncMessagesLogic(ctx, s.svcCtx)
	return l.SyncMessages(in)
}

func (s *MessageServiceServer) GetMessageByID(ctx context.Context, in *message.GetMessageByIDReq) (*message.GetMessageByIDResp, error) {
	l := logic.NewGetMessageByIDLogic(ctx, s.svcCtx)
	return l.GetMessageByID(in)
}

func (s *MessageServiceServer) BatchGetMessages(ctx context.Context, in *message.BatchGetMessagesReq) (*message.BatchGetMessagesResp, error) {
	l := logic.NewBatchGetMessagesLogic(ctx, s.svcCtx)
	return l.BatchGetMessages(in)
}

func (s *MessageServiceServer) GetAroundSeq(ctx context.Context, in *message.GetAroundSeqReq) (*message.GetMessagesResp, error) {
	l := logic.NewGetAroundSeqLogic(ctx, s.svcCtx)
	return l.GetAroundSeq(in)
}

func (s *MessageServiceServer) SearchMessages(ctx context.Context, in *message.SearchMessagesReq) (*message.SearchMessagesResp, error) {
	l := logic.NewSearchMessagesLogic(ctx, s.svcCtx)
	return l.SearchMessages(in)
}

// ========== Broadcast ==========
func (s *MessageServiceServer) SendBroadcast(ctx context.Context, in *message.SendBroadcastReq) (*message.SendBroadcastResp, error) {
	l := logic.NewSendBroadcastLogic(ctx, s.svcCtx)
	return l.SendBroadcast(in)
}

// ========== Bot Reply (called by bot-service) ==========
func (s *MessageServiceServer) SendBotReply(ctx context.Context, in *message.SendBotReplyReq) (*message.SendBotReplyResp, error) {
	l := logic.NewSendBotReplyLogic(ctx, s.svcCtx)
	return l.SendBotReply(in)
}

func (s *MessageServiceServer) SendSystemMessage(ctx context.Context, in *message.SendSystemMessageReq) (*message.SendMessageResp, error) {
	l := logic.NewSendSystemMessageLogic(ctx, s.svcCtx)
	return l.SendSystemMessage(in)
}
