// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: conversation-service/conversation.proto

package conversation

import (
	context "context"
	common "github.com/maomeng/aim/pkg/pb/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConversationService_CreateConversation_FullMethodName            = "/conversation.ConversationService/CreateConversation"
	ConversationService_GetConversation_FullMethodName               = "/conversation.ConversationService/GetConversation"
	ConversationService_ListConversations_FullMethodName             = "/conversation.ConversationService/ListConversations"
	ConversationService_UpdateConversation_FullMethodName            = "/conversation.ConversationService/UpdateConversation"
	ConversationService_DeleteConversation_FullMethodName            = "/conversation.ConversationService/DeleteConversation"
	ConversationService_AddMembers_FullMethodName                    = "/conversation.ConversationService/AddMembers"
	ConversationService_RemoveMembers_FullMethodName                 = "/conversation.ConversationService/RemoveMembers"
	ConversationService_GetMembers_FullMethodName                    = "/conversation.ConversationService/GetMembers"
	ConversationService_UpdateMember_FullMethodName                  = "/conversation.ConversationService/UpdateMember"
	ConversationService_IsMember_FullMethodName                      = "/conversation.ConversationService/IsMember"
	ConversationService_GetMuteStatus_FullMethodName                 = "/conversation.ConversationService/GetMuteStatus"
	ConversationService_GetMemberRole_FullMethodName                 = "/conversation.ConversationService/GetMemberRole"
	ConversationService_PreCheckSend_FullMethodName                  = "/conversation.ConversationService/PreCheckSend"
	ConversationService_MuteAll_FullMethodName                       = "/conversation.ConversationService/MuteAll"
	ConversationService_UnmuteAll_FullMethodName                     = "/conversation.ConversationService/UnmuteAll"
	ConversationService_MuteMember_FullMethodName                    = "/conversation.ConversationService/MuteMember"
	ConversationService_UnmuteMember_FullMethodName                  = "/conversation.ConversationService/UnmuteMember"
	ConversationService_SetAnnouncement_FullMethodName               = "/conversation.ConversationService/SetAnnouncement"
	ConversationService_DeleteAnnouncement_FullMethodName            = "/conversation.ConversationService/DeleteAnnouncement"
	ConversationService_TransferOwner_FullMethodName                 = "/conversation.ConversationService/TransferOwner"
	ConversationService_GetSettings_FullMethodName                   = "/conversation.ConversationService/GetSettings"
	ConversationService_UpdateSettings_FullMethodName                = "/conversation.ConversationService/UpdateSettings"
	ConversationService_UpdateConversationLastMessage_FullMethodName = "/conversation.ConversationService/UpdateConversationLastMessage"
	ConversationService_MarkAsRead_FullMethodName                    = "/conversation.ConversationService/MarkAsRead"
	ConversationService_GetReadStatus_FullMethodName                 = "/conversation.ConversationService/GetReadStatus"
	ConversationService_AddBot_FullMethodName                        = "/conversation.ConversationService/AddBot"
	ConversationService_RemoveBot_FullMethodName                     = "/conversation.ConversationService/RemoveBot"
	ConversationService_UpdateBot_FullMethodName                     = "/conversation.ConversationService/UpdateBot"
	ConversationService_ListBots_FullMethodName                      = "/conversation.ConversationService/ListBots"
)

// ConversationServiceClient is the client API for ConversationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationServiceClient interface {
	// ========== CRUD ==========
	CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*CreateConversationResp, error)
	GetConversation(ctx context.Context, in *GetConversationReq, opts ...grpc.CallOption) (*GetConversationResp, error)
	ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error)
	UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// ========== Members ==========
	AddMembers(ctx context.Context, in *AddMembersReq, opts ...grpc.CallOption) (*AddMembersResp, error)
	RemoveMembers(ctx context.Context, in *RemoveMembersReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	GetMembers(ctx context.Context, in *GetMembersReq, opts ...grpc.CallOption) (*GetMembersResp, error)
	UpdateMember(ctx context.Context, in *UpdateMemberReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// ========== Permissions (called by message-service) ==========
	IsMember(ctx context.Context, in *IsMemberReq, opts ...grpc.CallOption) (*IsMemberResp, error)
	GetMuteStatus(ctx context.Context, in *GetMuteStatusReq, opts ...grpc.CallOption) (*GetMuteStatusResp, error)
	GetMemberRole(ctx context.Context, in *GetMemberRoleReq, opts ...grpc.CallOption) (*GetMemberRoleResp, error)
	PreCheckSend(ctx context.Context, in *PreCheckSendReq, opts ...grpc.CallOption) (*PreCheckSendResp, error)
	// ========== Group Management ==========
	MuteAll(ctx context.Context, in *MuteAllReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	UnmuteAll(ctx context.Context, in *UnmuteAllReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	UnmuteMember(ctx context.Context, in *UnmuteMemberReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	SetAnnouncement(ctx context.Context, in *SetAnnouncementReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// ========== Settings ==========
	GetSettings(ctx context.Context, in *GetSettingsReq, opts ...grpc.CallOption) (*GetSettingsResp, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// ========== Last Message (called by message-service) ==========
	UpdateConversationLastMessage(ctx context.Context, in *UpdateConversationLastMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// ========== Read Status ==========
	MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	GetReadStatus(ctx context.Context, in *GetReadStatusReq, opts ...grpc.CallOption) (*GetReadStatusResp, error)
	// ========== Bot Management ==========
	AddBot(ctx context.Context, in *AddBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	RemoveBot(ctx context.Context, in *RemoveBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	UpdateBot(ctx context.Context, in *UpdateBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	ListBots(ctx context.Context, in *ListBotsReq, opts ...grpc.CallOption) (*ListBotsResp, error)
}

type conversationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationServiceClient(cc grpc.ClientConnInterface) ConversationServiceClient {
	return &conversationServiceClient{cc}
}

func (c *conversationServiceClient) CreateConversation(ctx context.Context, in *CreateConversationReq, opts ...grpc.CallOption) (*CreateConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConversationResp)
	err := c.cc.Invoke(ctx, ConversationService_CreateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetConversation(ctx context.Context, in *GetConversationReq, opts ...grpc.CallOption) (*GetConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationResp)
	err := c.cc.Invoke(ctx, ConversationService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResp)
	err := c.cc.Invoke(ctx, ConversationService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateConversation(ctx context.Context, in *UpdateConversationReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UpdateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) AddMembers(ctx context.Context, in *AddMembersReq, opts ...grpc.CallOption) (*AddMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMembersResp)
	err := c.cc.Invoke(ctx, ConversationService_AddMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) RemoveMembers(ctx context.Context, in *RemoveMembersReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_RemoveMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetMembers(ctx context.Context, in *GetMembersReq, opts ...grpc.CallOption) (*GetMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembersResp)
	err := c.cc.Invoke(ctx, ConversationService_GetMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateMember(ctx context.Context, in *UpdateMemberReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UpdateMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) IsMember(ctx context.Context, in *IsMemberReq, opts ...grpc.CallOption) (*IsMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsMemberResp)
	err := c.cc.Invoke(ctx, ConversationService_IsMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetMuteStatus(ctx context.Context, in *GetMuteStatusReq, opts ...grpc.CallOption) (*GetMuteStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMuteStatusResp)
	err := c.cc.Invoke(ctx, ConversationService_GetMuteStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetMemberRole(ctx context.Context, in *GetMemberRoleReq, opts ...grpc.CallOption) (*GetMemberRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberRoleResp)
	err := c.cc.Invoke(ctx, ConversationService_GetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) PreCheckSend(ctx context.Context, in *PreCheckSendReq, opts ...grpc.CallOption) (*PreCheckSendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCheckSendResp)
	err := c.cc.Invoke(ctx, ConversationService_PreCheckSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) MuteAll(ctx context.Context, in *MuteAllReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_MuteAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UnmuteAll(ctx context.Context, in *UnmuteAllReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UnmuteAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_MuteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UnmuteMember(ctx context.Context, in *UnmuteMemberReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UnmuteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) SetAnnouncement(ctx context.Context, in *SetAnnouncementReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_SetAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_DeleteAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_TransferOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetSettings(ctx context.Context, in *GetSettingsReq, opts ...grpc.CallOption) (*GetSettingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingsResp)
	err := c.cc.Invoke(ctx, ConversationService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateConversationLastMessage(ctx context.Context, in *UpdateConversationLastMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UpdateConversationLastMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_MarkAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetReadStatus(ctx context.Context, in *GetReadStatusReq, opts ...grpc.CallOption) (*GetReadStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadStatusResp)
	err := c.cc.Invoke(ctx, ConversationService_GetReadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) AddBot(ctx context.Context, in *AddBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_AddBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) RemoveBot(ctx context.Context, in *RemoveBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_RemoveBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateBot(ctx context.Context, in *UpdateBotReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, ConversationService_UpdateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) ListBots(ctx context.Context, in *ListBotsReq, opts ...grpc.CallOption) (*ListBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotsResp)
	err := c.cc.Invoke(ctx, ConversationService_ListBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationServiceServer is the server API for ConversationService service.
// All implementations must embed UnimplementedConversationServiceServer
// for forward compatibility.
type ConversationServiceServer interface {
	// ========== CRUD ==========
	CreateConversation(context.Context, *CreateConversationReq) (*CreateConversationResp, error)
	GetConversation(context.Context, *GetConversationReq) (*GetConversationResp, error)
	ListConversations(context.Context, *ListConversationsReq) (*ListConversationsResp, error)
	UpdateConversation(context.Context, *UpdateConversationReq) (*common.BaseResponse, error)
	DeleteConversation(context.Context, *DeleteConversationReq) (*common.BaseResponse, error)
	// ========== Members ==========
	AddMembers(context.Context, *AddMembersReq) (*AddMembersResp, error)
	RemoveMembers(context.Context, *RemoveMembersReq) (*common.BaseResponse, error)
	GetMembers(context.Context, *GetMembersReq) (*GetMembersResp, error)
	UpdateMember(context.Context, *UpdateMemberReq) (*common.BaseResponse, error)
	// ========== Permissions (called by message-service) ==========
	IsMember(context.Context, *IsMemberReq) (*IsMemberResp, error)
	GetMuteStatus(context.Context, *GetMuteStatusReq) (*GetMuteStatusResp, error)
	GetMemberRole(context.Context, *GetMemberRoleReq) (*GetMemberRoleResp, error)
	PreCheckSend(context.Context, *PreCheckSendReq) (*PreCheckSendResp, error)
	// ========== Group Management ==========
	MuteAll(context.Context, *MuteAllReq) (*common.BaseResponse, error)
	UnmuteAll(context.Context, *UnmuteAllReq) (*common.BaseResponse, error)
	MuteMember(context.Context, *MuteMemberReq) (*common.BaseResponse, error)
	UnmuteMember(context.Context, *UnmuteMemberReq) (*common.BaseResponse, error)
	SetAnnouncement(context.Context, *SetAnnouncementReq) (*common.BaseResponse, error)
	DeleteAnnouncement(context.Context, *DeleteAnnouncementReq) (*common.BaseResponse, error)
	TransferOwner(context.Context, *TransferOwnerReq) (*common.BaseResponse, error)
	// ========== Settings ==========
	GetSettings(context.Context, *GetSettingsReq) (*GetSettingsResp, error)
	UpdateSettings(context.Context, *UpdateSettingsReq) (*common.BaseResponse, error)
	// ========== Last Message (called by message-service) ==========
	UpdateConversationLastMessage(context.Context, *UpdateConversationLastMessageReq) (*common.BaseResponse, error)
	// ========== Read Status ==========
	MarkAsRead(context.Context, *MarkAsReadReq) (*common.BaseResponse, error)
	GetReadStatus(context.Context, *GetReadStatusReq) (*GetReadStatusResp, error)
	// ========== Bot Management ==========
	AddBot(context.Context, *AddBotReq) (*common.BaseResponse, error)
	RemoveBot(context.Context, *RemoveBotReq) (*common.BaseResponse, error)
	UpdateBot(context.Context, *UpdateBotReq) (*common.BaseResponse, error)
	ListBots(context.Context, *ListBotsReq) (*ListBotsResp, error)
	mustEmbedUnimplementedConversationServiceServer()
}

// UnimplementedConversationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationServiceServer struct{}

func (UnimplementedConversationServiceServer) CreateConversation(context.Context, *CreateConversationReq) (*CreateConversationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConversation not implemented")
}
func (UnimplementedConversationServiceServer) GetConversation(context.Context, *GetConversationReq) (*GetConversationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedConversationServiceServer) ListConversations(context.Context, *ListConversationsReq) (*ListConversationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedConversationServiceServer) UpdateConversation(context.Context, *UpdateConversationReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConversation not implemented")
}
func (UnimplementedConversationServiceServer) DeleteConversation(context.Context, *DeleteConversationReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedConversationServiceServer) AddMembers(context.Context, *AddMembersReq) (*AddMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMembers not implemented")
}
func (UnimplementedConversationServiceServer) RemoveMembers(context.Context, *RemoveMembersReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMembers not implemented")
}
func (UnimplementedConversationServiceServer) GetMembers(context.Context, *GetMembersReq) (*GetMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembers not implemented")
}
func (UnimplementedConversationServiceServer) UpdateMember(context.Context, *UpdateMemberReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMember not implemented")
}
func (UnimplementedConversationServiceServer) IsMember(context.Context, *IsMemberReq) (*IsMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsMember not implemented")
}
func (UnimplementedConversationServiceServer) GetMuteStatus(context.Context, *GetMuteStatusReq) (*GetMuteStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMuteStatus not implemented")
}
func (UnimplementedConversationServiceServer) GetMemberRole(context.Context, *GetMemberRoleReq) (*GetMemberRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberRole not implemented")
}
func (UnimplementedConversationServiceServer) PreCheckSend(context.Context, *PreCheckSendReq) (*PreCheckSendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PreCheckSend not implemented")
}
func (UnimplementedConversationServiceServer) MuteAll(context.Context, *MuteAllReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MuteAll not implemented")
}
func (UnimplementedConversationServiceServer) UnmuteAll(context.Context, *UnmuteAllReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmuteAll not implemented")
}
func (UnimplementedConversationServiceServer) MuteMember(context.Context, *MuteMemberReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MuteMember not implemented")
}
func (UnimplementedConversationServiceServer) UnmuteMember(context.Context, *UnmuteMemberReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmuteMember not implemented")
}
func (UnimplementedConversationServiceServer) SetAnnouncement(context.Context, *SetAnnouncementReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAnnouncement not implemented")
}
func (UnimplementedConversationServiceServer) DeleteAnnouncement(context.Context, *DeleteAnnouncementReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAnnouncement not implemented")
}
func (UnimplementedConversationServiceServer) TransferOwner(context.Context, *TransferOwnerReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwner not implemented")
}
func (UnimplementedConversationServiceServer) GetSettings(context.Context, *GetSettingsReq) (*GetSettingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedConversationServiceServer) UpdateSettings(context.Context, *UpdateSettingsReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedConversationServiceServer) UpdateConversationLastMessage(context.Context, *UpdateConversationLastMessageReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConversationLastMessage not implemented")
}
func (UnimplementedConversationServiceServer) MarkAsRead(context.Context, *MarkAsReadReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAsRead not implemented")
}
func (UnimplementedConversationServiceServer) GetReadStatus(context.Context, *GetReadStatusReq) (*GetReadStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadStatus not implemented")
}
func (UnimplementedConversationServiceServer) AddBot(context.Context, *AddBotReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBot not implemented")
}
func (UnimplementedConversationServiceServer) RemoveBot(context.Context, *RemoveBotReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBot not implemented")
}
func (UnimplementedConversationServiceServer) UpdateBot(context.Context, *UpdateBotReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBot not implemented")
}
func (UnimplementedConversationServiceServer) ListBots(context.Context, *ListBotsReq) (*ListBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBots not implemented")
}
func (UnimplementedConversationServiceServer) mustEmbedUnimplementedConversationServiceServer() {}
func (UnimplementedConversationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConversationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationServiceServer will
// result in compilation errors.
type UnsafeConversationServiceServer interface {
	mustEmbedUnimplementedConversationServiceServer()
}

func RegisterConversationServiceServer(s grpc.ServiceRegistrar, srv ConversationServiceServer) {
	// If the following call panics, it indicates UnimplementedConversationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationService_ServiceDesc, srv)
}

func _ConversationService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_CreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).CreateConversation(ctx, req.(*CreateConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversation(ctx, req.(*GetConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).ListConversations(ctx, req.(*ListConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UpdateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateConversation(ctx, req.(*UpdateConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).DeleteConversation(ctx, req.(*DeleteConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_AddMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).AddMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_AddMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).AddMembers(ctx, req.(*AddMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_RemoveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).RemoveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_RemoveMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).RemoveMembers(ctx, req.(*RemoveMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetMembers(ctx, req.(*GetMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UpdateMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateMember(ctx, req.(*UpdateMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_IsMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).IsMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_IsMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).IsMember(ctx, req.(*IsMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetMuteStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMuteStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetMuteStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetMuteStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetMuteStatus(ctx, req.(*GetMuteStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetMemberRole(ctx, req.(*GetMemberRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_PreCheckSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCheckSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).PreCheckSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_PreCheckSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).PreCheckSend(ctx, req.(*PreCheckSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_MuteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).MuteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_MuteAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).MuteAll(ctx, req.(*MuteAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UnmuteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmuteAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UnmuteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UnmuteAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UnmuteAll(ctx, req.(*UnmuteAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_MuteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).MuteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_MuteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).MuteMember(ctx, req.(*MuteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UnmuteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmuteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UnmuteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UnmuteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UnmuteMember(ctx, req.(*UnmuteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SetAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnnouncementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SetAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_SetAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SetAnnouncement(ctx, req.(*SetAnnouncementReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_DeleteAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnnouncementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).DeleteAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_DeleteAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).DeleteAnnouncement(ctx, req.(*DeleteAnnouncementReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_TransferOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).TransferOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_TransferOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).TransferOwner(ctx, req.(*TransferOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetSettings(ctx, req.(*GetSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateSettings(ctx, req.(*UpdateSettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateConversationLastMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationLastMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateConversationLastMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UpdateConversationLastMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateConversationLastMessage(ctx, req.(*UpdateConversationLastMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_MarkAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).MarkAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_MarkAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).MarkAsRead(ctx, req.(*MarkAsReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetReadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetReadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetReadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetReadStatus(ctx, req.(*GetReadStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_AddBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).AddBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_AddBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).AddBot(ctx, req.(*AddBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_RemoveBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).RemoveBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_RemoveBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).RemoveBot(ctx, req.(*RemoveBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UpdateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateBot(ctx, req.(*UpdateBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_ListBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).ListBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_ListBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).ListBots(ctx, req.(*ListBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationService_ServiceDesc is the grpc.ServiceDesc for ConversationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conversation.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversation",
			Handler:    _ConversationService_CreateConversation_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _ConversationService_GetConversation_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _ConversationService_ListConversations_Handler,
		},
		{
			MethodName: "UpdateConversation",
			Handler:    _ConversationService_UpdateConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _ConversationService_DeleteConversation_Handler,
		},
		{
			MethodName: "AddMembers",
			Handler:    _ConversationService_AddMembers_Handler,
		},
		{
			MethodName: "RemoveMembers",
			Handler:    _ConversationService_RemoveMembers_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _ConversationService_GetMembers_Handler,
		},
		{
			MethodName: "UpdateMember",
			Handler:    _ConversationService_UpdateMember_Handler,
		},
		{
			MethodName: "IsMember",
			Handler:    _ConversationService_IsMember_Handler,
		},
		{
			MethodName: "GetMuteStatus",
			Handler:    _ConversationService_GetMuteStatus_Handler,
		},
		{
			MethodName: "GetMemberRole",
			Handler:    _ConversationService_GetMemberRole_Handler,
		},
		{
			MethodName: "PreCheckSend",
			Handler:    _ConversationService_PreCheckSend_Handler,
		},
		{
			MethodName: "MuteAll",
			Handler:    _ConversationService_MuteAll_Handler,
		},
		{
			MethodName: "UnmuteAll",
			Handler:    _ConversationService_UnmuteAll_Handler,
		},
		{
			MethodName: "MuteMember",
			Handler:    _ConversationService_MuteMember_Handler,
		},
		{
			MethodName: "UnmuteMember",
			Handler:    _ConversationService_UnmuteMember_Handler,
		},
		{
			MethodName: "SetAnnouncement",
			Handler:    _ConversationService_SetAnnouncement_Handler,
		},
		{
			MethodName: "DeleteAnnouncement",
			Handler:    _ConversationService_DeleteAnnouncement_Handler,
		},
		{
			MethodName: "TransferOwner",
			Handler:    _ConversationService_TransferOwner_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _ConversationService_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _ConversationService_UpdateSettings_Handler,
		},
		{
			MethodName: "UpdateConversationLastMessage",
			Handler:    _ConversationService_UpdateConversationLastMessage_Handler,
		},
		{
			MethodName: "MarkAsRead",
			Handler:    _ConversationService_MarkAsRead_Handler,
		},
		{
			MethodName: "GetReadStatus",
			Handler:    _ConversationService_GetReadStatus_Handler,
		},
		{
			MethodName: "AddBot",
			Handler:    _ConversationService_AddBot_Handler,
		},
		{
			MethodName: "RemoveBot",
			Handler:    _ConversationService_RemoveBot_Handler,
		},
		{
			MethodName: "UpdateBot",
			Handler:    _ConversationService_UpdateBot_Handler,
		},
		{
			MethodName: "ListBots",
			Handler:    _ConversationService_ListBots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conversation-service/conversation.proto",
}
