server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index swagger.html;

    location /openapi.yaml {
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri /swagger.html;
    }
}
