// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: ws-gateway/push.proto

package push

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalPushService_PushToUsers_FullMethodName = "/push.InternalPushService/PushToUsers"
	InternalPushService_PushToBot_FullMethodName   = "/push.InternalPushService/PushToBot"
	InternalPushService_PushToConv_FullMethodName  = "/push.InternalPushService/PushToConv"
	InternalPushService_PushToUser_FullMethodName  = "/push.InternalPushService/PushToUser"
)

// InternalPushServiceClient is the client API for InternalPushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalPushServiceClient interface {
	PushToUsers(ctx context.Context, in *PushToUsersReq, opts ...grpc.CallOption) (*PushToUsersResp, error)
	PushToBot(ctx context.Context, in *PushToBotReq, opts ...grpc.CallOption) (*PushToBotResp, error)
	PushToConv(ctx context.Context, in *PushToConvReq, opts ...grpc.CallOption) (*PushToConvResp, error)
	PushToUser(ctx context.Context, in *PushToUserReq, opts ...grpc.CallOption) (*PushToUserResp, error)
}

type internalPushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalPushServiceClient(cc grpc.ClientConnInterface) InternalPushServiceClient {
	return &internalPushServiceClient{cc}
}

func (c *internalPushServiceClient) PushToUsers(ctx context.Context, in *PushToUsersReq, opts ...grpc.CallOption) (*PushToUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToUsersResp)
	err := c.cc.Invoke(ctx, InternalPushService_PushToUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalPushServiceClient) PushToBot(ctx context.Context, in *PushToBotReq, opts ...grpc.CallOption) (*PushToBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToBotResp)
	err := c.cc.Invoke(ctx, InternalPushService_PushToBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalPushServiceClient) PushToConv(ctx context.Context, in *PushToConvReq, opts ...grpc.CallOption) (*PushToConvResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToConvResp)
	err := c.cc.Invoke(ctx, InternalPushService_PushToConv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalPushServiceClient) PushToUser(ctx context.Context, in *PushToUserReq, opts ...grpc.CallOption) (*PushToUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToUserResp)
	err := c.cc.Invoke(ctx, InternalPushService_PushToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalPushServiceServer is the server API for InternalPushService service.
// All implementations must embed UnimplementedInternalPushServiceServer
// for forward compatibility.
type InternalPushServiceServer interface {
	PushToUsers(context.Context, *PushToUsersReq) (*PushToUsersResp, error)
	PushToBot(context.Context, *PushToBotReq) (*PushToBotResp, error)
	PushToConv(context.Context, *PushToConvReq) (*PushToConvResp, error)
	PushToUser(context.Context, *PushToUserReq) (*PushToUserResp, error)
	mustEmbedUnimplementedInternalPushServiceServer()
}

// UnimplementedInternalPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalPushServiceServer struct{}

func (UnimplementedInternalPushServiceServer) PushToUsers(context.Context, *PushToUsersReq) (*PushToUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToUsers not implemented")
}
func (UnimplementedInternalPushServiceServer) PushToBot(context.Context, *PushToBotReq) (*PushToBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToBot not implemented")
}
func (UnimplementedInternalPushServiceServer) PushToConv(context.Context, *PushToConvReq) (*PushToConvResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToConv not implemented")
}
func (UnimplementedInternalPushServiceServer) PushToUser(context.Context, *PushToUserReq) (*PushToUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToUser not implemented")
}
func (UnimplementedInternalPushServiceServer) mustEmbedUnimplementedInternalPushServiceServer() {}
func (UnimplementedInternalPushServiceServer) testEmbeddedByValue()                             {}

// UnsafeInternalPushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalPushServiceServer will
// result in compilation errors.
type UnsafeInternalPushServiceServer interface {
	mustEmbedUnimplementedInternalPushServiceServer()
}

func RegisterInternalPushServiceServer(s grpc.ServiceRegistrar, srv InternalPushServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalPushService_ServiceDesc, srv)
}

func _InternalPushService_PushToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalPushServiceServer).PushToUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalPushService_PushToUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalPushServiceServer).PushToUsers(ctx, req.(*PushToUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalPushService_PushToBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalPushServiceServer).PushToBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalPushService_PushToBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalPushServiceServer).PushToBot(ctx, req.(*PushToBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalPushService_PushToConv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToConvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalPushServiceServer).PushToConv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalPushService_PushToConv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalPushServiceServer).PushToConv(ctx, req.(*PushToConvReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalPushService_PushToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalPushServiceServer).PushToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalPushService_PushToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalPushServiceServer).PushToUser(ctx, req.(*PushToUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalPushService_ServiceDesc is the grpc.ServiceDesc for InternalPushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalPushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "push.InternalPushService",
	HandlerType: (*InternalPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToUsers",
			Handler:    _InternalPushService_PushToUsers_Handler,
		},
		{
			MethodName: "PushToBot",
			Handler:    _InternalPushService_PushToBot_Handler,
		},
		{
			MethodName: "PushToConv",
			Handler:    _InternalPushService_PushToConv_Handler,
		},
		{
			MethodName: "PushToUser",
			Handler:    _InternalPushService_PushToUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ws-gateway/push.proto",
}
