apiVersion: v1
kind: Service
metadata:
  name: {{ include "aim-service.fullname" . }}
  labels:
    {{- include "aim-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "aim-service.fullname" . }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      name: grpc
      protocol: TCP
    {{- if .Values.service.httpPort }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http
      protocol: TCP
    {{- end }}
    {{- if .Values.service.wsPort }}
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      name: ws
      protocol: TCP
    {{- end }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics
      protocol: TCP
