// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	"github.com/maomeng/aim/app/user-service/pb/user"

	"github.com/maomeng/aim/pkg/pb/common"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetStatusReq    = user.BatchGetStatusReq
	BatchGetStatusResp   = user.BatchGetStatusResp
	BatchGetUserInfoReq  = user.BatchGetUserInfoReq
	BatchGetUserInfoResp = user.BatchGetUserInfoResp
	BindEmailReq         = user.BindEmailReq
	BindPhoneReq         = user.BindPhoneReq
	DeviceInfo           = user.DeviceInfo
	GetSessionsResp      = user.GetSessionsResp
	GetSettingsResp      = user.GetSettingsResp
	GetUserInfoReq       = user.GetUserInfoReq
	LoginReq             = user.LoginReq
	LoginResp            = user.LoginResp
	LogoutReq            = user.LogoutReq
	OAuthLoginReq        = user.OAuthLoginReq
	RefreshTokenReq      = user.RefreshTokenReq
	RefreshTokenResp     = user.RefreshTokenResp
	RegisterReq          = user.RegisterReq
	RegisterResp         = user.RegisterResp
	RevokeSessionReq     = user.RevokeSessionReq
	SearchUsersReq       = user.SearchUsersReq
	SearchUsersResp      = user.SearchUsersResp
	ListAllUserIDsResp   = user.ListAllUserIDsResp
	SessionInfo          = user.SessionInfo
	TokenPair            = user.TokenPair
	UpdatePasswordReq    = user.UpdatePasswordReq
	UpdateProfileReq     = user.UpdateProfileReq
	UpdateSettingsReq    = user.UpdateSettingsReq
	UserInfo             = user.UserInfo
	UserStatus           = user.UserStatus
	ValidateTokenReq     = user.ValidateTokenReq
	ValidateTokenResp    = user.ValidateTokenResp

	UserService interface {
		// ========== Auth ==========
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		OAuthLogin(ctx context.Context, in *OAuthLoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		GetSessions(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetSessionsResp, error)
		RevokeSession(ctx context.Context, in *RevokeSessionReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		// ========== User Profile ==========
		GetProfile(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UserInfo, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UserInfo, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		BindPhone(ctx context.Context, in *BindPhoneReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		BindEmail(ctx context.Context, in *BindEmailReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*UserInfo, error)
		BatchGetUserInfo(ctx context.Context, in *BatchGetUserInfoReq, opts ...grpc.CallOption) (*BatchGetUserInfoResp, error)
		SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersResp, error)
		ListAllUserIDs(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListAllUserIDsResp, error)
		BatchGetStatus(ctx context.Context, in *BatchGetStatusReq, opts ...grpc.CallOption) (*BatchGetStatusResp, error)
		GetSettings(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetSettingsResp, error)
		UpdateSettings(ctx context.Context, in *UpdateSettingsReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// ========== Auth ==========
func (m *defaultUserService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultUserService) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultUserService) OAuthLogin(ctx context.Context, in *OAuthLoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.OAuthLogin(ctx, in, opts...)
}

func (m *defaultUserService) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultUserService) GetSessions(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetSessionsResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetSessions(ctx, in, opts...)
}

func (m *defaultUserService) RevokeSession(ctx context.Context, in *RevokeSessionReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.RevokeSession(ctx, in, opts...)
}

// ========== User Profile ==========
func (m *defaultUserService) GetProfile(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultUserService) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultUserService) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}

func (m *defaultUserService) BindPhone(ctx context.Context, in *BindPhoneReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.BindPhone(ctx, in, opts...)
}

func (m *defaultUserService) BindEmail(ctx context.Context, in *BindEmailReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.BindEmail(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) BatchGetUserInfo(ctx context.Context, in *BatchGetUserInfoReq, opts ...grpc.CallOption) (*BatchGetUserInfoResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.BatchGetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.SearchUsers(ctx, in, opts...)
}

func (m *defaultUserService) ListAllUserIDs(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*ListAllUserIDsResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ListAllUserIDs(ctx, in, opts...)
}

func (m *defaultUserService) BatchGetStatus(ctx context.Context, in *BatchGetStatusReq, opts ...grpc.CallOption) (*BatchGetStatusResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.BatchGetStatus(ctx, in, opts...)
}

func (m *defaultUserService) GetSettings(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*GetSettingsResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetSettings(ctx, in, opts...)
}

func (m *defaultUserService) UpdateSettings(ctx context.Context, in *UpdateSettingsReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateSettings(ctx, in, opts...)
}
