// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: friend-service/friend.proto

package friend

import (
	context "context"
	common "github.com/maomeng/aim/pkg/pb/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendService_SendRequest_FullMethodName         = "/friend.FriendService/SendRequest"
	FriendService_AcceptRequest_FullMethodName       = "/friend.FriendService/AcceptRequest"
	FriendService_RejectRequest_FullMethodName       = "/friend.FriendService/RejectRequest"
	FriendService_CancelRequest_FullMethodName       = "/friend.FriendService/CancelRequest"
	FriendService_ListPendingRequests_FullMethodName = "/friend.FriendService/ListPendingRequests"
	FriendService_ListSentRequests_FullMethodName    = "/friend.FriendService/ListSentRequests"
	FriendService_ListFriends_FullMethodName         = "/friend.FriendService/ListFriends"
	FriendService_DeleteFriend_FullMethodName        = "/friend.FriendService/DeleteFriend"
	FriendService_SetRemark_FullMethodName           = "/friend.FriendService/SetRemark"
	FriendService_SetGroup_FullMethodName            = "/friend.FriendService/SetGroup"
	FriendService_CreateGroup_FullMethodName         = "/friend.FriendService/CreateGroup"
	FriendService_RenameGroup_FullMethodName         = "/friend.FriendService/RenameGroup"
	FriendService_DeleteGroup_FullMethodName         = "/friend.FriendService/DeleteGroup"
	FriendService_ListGroups_FullMethodName          = "/friend.FriendService/ListGroups"
	FriendService_BlockUser_FullMethodName           = "/friend.FriendService/BlockUser"
	FriendService_UnblockUser_FullMethodName         = "/friend.FriendService/UnblockUser"
	FriendService_ListBlacklist_FullMethodName       = "/friend.FriendService/ListBlacklist"
	FriendService_IsBlocked_FullMethodName           = "/friend.FriendService/IsBlocked"
)

// FriendServiceClient is the client API for FriendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendServiceClient interface {
	// ========== Friend Requests ==========
	SendRequest(ctx context.Context, in *SendRequestReq, opts ...grpc.CallOption) (*SendRequestResp, error)
	AcceptRequest(ctx context.Context, in *AcceptRequestReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	RejectRequest(ctx context.Context, in *RejectRequestReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	CancelRequest(ctx context.Context, in *CancelRequestReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	ListPendingRequests(ctx context.Context, in *ListPendingRequestsReq, opts ...grpc.CallOption) (*ListRequestsResp, error)
	ListSentRequests(ctx context.Context, in *ListSentRequestsReq, opts ...grpc.CallOption) (*ListRequestsResp, error)
	// ========== Friend Management ==========
	ListFriends(ctx context.Context, in *ListFriendsReq, opts ...grpc.CallOption) (*ListFriendsResp, error)
	DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	SetRemark(ctx context.Context, in *SetRemarkReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	SetGroup(ctx context.Context, in *SetGroupReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	// ========== Friend Groups ==========
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	RenameGroup(ctx context.Context, in *RenameGroupReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error)
	// ========== Blacklist ==========
	BlockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	UnblockUser(ctx context.Context, in *UnblockUserReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
	ListBlacklist(ctx context.Context, in *ListBlacklistReq, opts ...grpc.CallOption) (*ListBlacklistResp, error)
	IsBlocked(ctx context.Context, in *IsBlockedReq, opts ...grpc.CallOption) (*IsBlockedResp, error)
}

type friendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendServiceClient(cc grpc.ClientConnInterface) FriendServiceClient {
	return &friendServiceClient{cc}
}

func (c *friendServiceClient) SendRequest(ctx context.Context, in *SendRequestReq, opts ...grpc.CallOption) (*SendRequestResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRequestResp)
	err := c.cc.Invoke(ctx, FriendService_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) AcceptRequest(ctx context.Context, in *AcceptRequestReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_AcceptRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) RejectRequest(ctx context.Context, in *RejectRequestReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_RejectRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CancelRequest(ctx context.Context, in *CancelRequestReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_CancelRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListPendingRequests(ctx context.Context, in *ListPendingRequestsReq, opts ...grpc.CallOption) (*ListRequestsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequestsResp)
	err := c.cc.Invoke(ctx, FriendService_ListPendingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListSentRequests(ctx context.Context, in *ListSentRequestsReq, opts ...grpc.CallOption) (*ListRequestsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequestsResp)
	err := c.cc.Invoke(ctx, FriendService_ListSentRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListFriends(ctx context.Context, in *ListFriendsReq, opts ...grpc.CallOption) (*ListFriendsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResp)
	err := c.cc.Invoke(ctx, FriendService_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SetRemark(ctx context.Context, in *SetRemarkReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_SetRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SetGroup(ctx context.Context, in *SetGroupReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_SetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, FriendService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) RenameGroup(ctx context.Context, in *RenameGroupReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_RenameGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResp)
	err := c.cc.Invoke(ctx, FriendService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) BlockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) UnblockUser(ctx context.Context, in *UnblockUserReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResponse)
	err := c.cc.Invoke(ctx, FriendService_UnblockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListBlacklist(ctx context.Context, in *ListBlacklistReq, opts ...grpc.CallOption) (*ListBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistResp)
	err := c.cc.Invoke(ctx, FriendService_ListBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) IsBlocked(ctx context.Context, in *IsBlockedReq, opts ...grpc.CallOption) (*IsBlockedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsBlockedResp)
	err := c.cc.Invoke(ctx, FriendService_IsBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServiceServer is the server API for FriendService service.
// All implementations must embed UnimplementedFriendServiceServer
// for forward compatibility.
type FriendServiceServer interface {
	// ========== Friend Requests ==========
	SendRequest(context.Context, *SendRequestReq) (*SendRequestResp, error)
	AcceptRequest(context.Context, *AcceptRequestReq) (*common.BaseResponse, error)
	RejectRequest(context.Context, *RejectRequestReq) (*common.BaseResponse, error)
	CancelRequest(context.Context, *CancelRequestReq) (*common.BaseResponse, error)
	ListPendingRequests(context.Context, *ListPendingRequestsReq) (*ListRequestsResp, error)
	ListSentRequests(context.Context, *ListSentRequestsReq) (*ListRequestsResp, error)
	// ========== Friend Management ==========
	ListFriends(context.Context, *ListFriendsReq) (*ListFriendsResp, error)
	DeleteFriend(context.Context, *DeleteFriendReq) (*common.BaseResponse, error)
	SetRemark(context.Context, *SetRemarkReq) (*common.BaseResponse, error)
	SetGroup(context.Context, *SetGroupReq) (*common.BaseResponse, error)
	// ========== Friend Groups ==========
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	RenameGroup(context.Context, *RenameGroupReq) (*common.BaseResponse, error)
	DeleteGroup(context.Context, *DeleteGroupReq) (*common.BaseResponse, error)
	ListGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error)
	// ========== Blacklist ==========
	BlockUser(context.Context, *BlockUserReq) (*common.BaseResponse, error)
	UnblockUser(context.Context, *UnblockUserReq) (*common.BaseResponse, error)
	ListBlacklist(context.Context, *ListBlacklistReq) (*ListBlacklistResp, error)
	IsBlocked(context.Context, *IsBlockedReq) (*IsBlockedResp, error)
	mustEmbedUnimplementedFriendServiceServer()
}

// UnimplementedFriendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendServiceServer struct{}

func (UnimplementedFriendServiceServer) SendRequest(context.Context, *SendRequestReq) (*SendRequestResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedFriendServiceServer) AcceptRequest(context.Context, *AcceptRequestReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRequest not implemented")
}
func (UnimplementedFriendServiceServer) RejectRequest(context.Context, *RejectRequestReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectRequest not implemented")
}
func (UnimplementedFriendServiceServer) CancelRequest(context.Context, *CancelRequestReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRequest not implemented")
}
func (UnimplementedFriendServiceServer) ListPendingRequests(context.Context, *ListPendingRequestsReq) (*ListRequestsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingRequests not implemented")
}
func (UnimplementedFriendServiceServer) ListSentRequests(context.Context, *ListSentRequestsReq) (*ListRequestsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSentRequests not implemented")
}
func (UnimplementedFriendServiceServer) ListFriends(context.Context, *ListFriendsReq) (*ListFriendsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedFriendServiceServer) DeleteFriend(context.Context, *DeleteFriendReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (UnimplementedFriendServiceServer) SetRemark(context.Context, *SetRemarkReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRemark not implemented")
}
func (UnimplementedFriendServiceServer) SetGroup(context.Context, *SetGroupReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroup not implemented")
}
func (UnimplementedFriendServiceServer) CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedFriendServiceServer) RenameGroup(context.Context, *RenameGroupReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameGroup not implemented")
}
func (UnimplementedFriendServiceServer) DeleteGroup(context.Context, *DeleteGroupReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedFriendServiceServer) ListGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedFriendServiceServer) BlockUser(context.Context, *BlockUserReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedFriendServiceServer) UnblockUser(context.Context, *UnblockUserReq) (*common.BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockUser not implemented")
}
func (UnimplementedFriendServiceServer) ListBlacklist(context.Context, *ListBlacklistReq) (*ListBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlacklist not implemented")
}
func (UnimplementedFriendServiceServer) IsBlocked(context.Context, *IsBlockedReq) (*IsBlockedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsBlocked not implemented")
}
func (UnimplementedFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {}
func (UnimplementedFriendServiceServer) testEmbeddedByValue()                       {}

// UnsafeFriendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServiceServer will
// result in compilation errors.
type UnsafeFriendServiceServer interface {
	mustEmbedUnimplementedFriendServiceServer()
}

func RegisterFriendServiceServer(s grpc.ServiceRegistrar, srv FriendServiceServer) {
	// If the following call panics, it indicates UnimplementedFriendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendService_ServiceDesc, srv)
}

func _FriendService_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SendRequest(ctx, req.(*SendRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_AcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).AcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_AcceptRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).AcceptRequest(ctx, req.(*AcceptRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_RejectRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).RejectRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_RejectRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).RejectRequest(ctx, req.(*RejectRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CancelRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CancelRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CancelRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CancelRequest(ctx, req.(*CancelRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListPendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListPendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListPendingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListPendingRequests(ctx, req.(*ListPendingRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListSentRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSentRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListSentRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListSentRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListSentRequests(ctx, req.(*ListSentRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListFriends(ctx, req.(*ListFriendsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteFriend(ctx, req.(*DeleteFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SetRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRemarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SetRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SetRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SetRemark(ctx, req.(*SetRemarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SetGroup(ctx, req.(*SetGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_RenameGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).RenameGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_RenameGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).RenameGroup(ctx, req.(*RenameGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteGroup(ctx, req.(*DeleteGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListGroups(ctx, req.(*ListGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).BlockUser(ctx, req.(*BlockUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_UnblockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).UnblockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_UnblockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).UnblockUser(ctx, req.(*UnblockUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListBlacklist(ctx, req.(*ListBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_IsBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBlockedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).IsBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_IsBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).IsBlocked(ctx, req.(*IsBlockedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendService_ServiceDesc is the grpc.ServiceDesc for FriendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friend.FriendService",
	HandlerType: (*FriendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _FriendService_SendRequest_Handler,
		},
		{
			MethodName: "AcceptRequest",
			Handler:    _FriendService_AcceptRequest_Handler,
		},
		{
			MethodName: "RejectRequest",
			Handler:    _FriendService_RejectRequest_Handler,
		},
		{
			MethodName: "CancelRequest",
			Handler:    _FriendService_CancelRequest_Handler,
		},
		{
			MethodName: "ListPendingRequests",
			Handler:    _FriendService_ListPendingRequests_Handler,
		},
		{
			MethodName: "ListSentRequests",
			Handler:    _FriendService_ListSentRequests_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _FriendService_ListFriends_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _FriendService_DeleteFriend_Handler,
		},
		{
			MethodName: "SetRemark",
			Handler:    _FriendService_SetRemark_Handler,
		},
		{
			MethodName: "SetGroup",
			Handler:    _FriendService_SetGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _FriendService_CreateGroup_Handler,
		},
		{
			MethodName: "RenameGroup",
			Handler:    _FriendService_RenameGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _FriendService_DeleteGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _FriendService_ListGroups_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _FriendService_BlockUser_Handler,
		},
		{
			MethodName: "UnblockUser",
			Handler:    _FriendService_UnblockUser_Handler,
		},
		{
			MethodName: "ListBlacklist",
			Handler:    _FriendService_ListBlacklist_Handler,
		},
		{
			MethodName: "IsBlocked",
			Handler:    _FriendService_IsBlocked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friend-service/friend.proto",
}
