// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: realtime/realtime.proto

package realtime

import (
	common "github.com/maomeng/aim/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,7,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_realtime_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListNotificationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *common.Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Type          *int32                 `protobuf:"varint,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	IsRead        *bool                  `protobuf:"varint,3,opt,name=is_read,json=isRead,proto3,oneof" json:"is_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsReq) Reset() {
	*x = ListNotificationsReq{}
	mi := &file_realtime_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsReq) ProtoMessage() {}

func (x *ListNotificationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsReq.ProtoReflect.Descriptor instead.
func (*ListNotificationsReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsReq) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsReq) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *ListNotificationsReq) GetIsRead() bool {
	if x != nil && x.IsRead != nil {
		return *x.IsRead
	}
	return false
}

type ListNotificationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Pagination    *common.PaginationResp `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResp) Reset() {
	*x = ListNotificationsResp{}
	mi := &file_realtime_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResp) ProtoMessage() {}

func (x *ListNotificationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResp.ProtoReflect.Descriptor instead.
func (*ListNotificationsResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsResp) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResp) GetPagination() *common.PaginationResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetUnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	mi := &file_realtime_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{3}
}

type GetUnreadCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResp) Reset() {
	*x = GetUnreadCountResp{}
	mi := &file_realtime_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResp) ProtoMessage() {}

func (x *GetUnreadCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResp.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{4}
}

func (x *GetUnreadCountResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarkReadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_realtime_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadReq) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type MarkReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResp) Reset() {
	*x = MarkReadResp{}
	mi := &file_realtime_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResp) ProtoMessage() {}

func (x *MarkReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResp.ProtoReflect.Descriptor instead.
func (*MarkReadResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{6}
}

type MarkAllReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadReq) Reset() {
	*x = MarkAllReadReq{}
	mi := &file_realtime_realtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadReq) ProtoMessage() {}

func (x *MarkAllReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadReq.ProtoReflect.Descriptor instead.
func (*MarkAllReadReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{7}
}

type MarkAllReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadResp) Reset() {
	*x = MarkAllReadResp{}
	mi := &file_realtime_realtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadResp) ProtoMessage() {}

func (x *MarkAllReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadResp.ProtoReflect.Descriptor instead.
func (*MarkAllReadResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{8}
}

type DeleteNotificationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationReq) Reset() {
	*x = DeleteNotificationReq{}
	mi := &file_realtime_realtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationReq) ProtoMessage() {}

func (x *DeleteNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationReq.ProtoReflect.Descriptor instead.
func (*DeleteNotificationReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNotificationReq) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type DeleteNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResp) Reset() {
	*x = DeleteNotificationResp{}
	mi := &file_realtime_realtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResp) ProtoMessage() {}

func (x *DeleteNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResp.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{10}
}

type PushNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotificationReq) Reset() {
	*x = PushNotificationReq{}
	mi := &file_realtime_realtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationReq) ProtoMessage() {}

func (x *PushNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationReq.ProtoReflect.Descriptor instead.
func (*PushNotificationReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{11}
}

func (x *PushNotificationReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *PushNotificationReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PushNotificationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushNotificationReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushNotificationReq) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type PushNotificationResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FirstNotificationId int64                  `protobuf:"varint,1,opt,name=first_notification_id,json=firstNotificationId,proto3" json:"first_notification_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PushNotificationResp) Reset() {
	*x = PushNotificationResp{}
	mi := &file_realtime_realtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationResp) ProtoMessage() {}

func (x *PushNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationResp.ProtoReflect.Descriptor instead.
func (*PushNotificationResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{12}
}

func (x *PushNotificationResp) GetFirstNotificationId() int64 {
	if x != nil {
		return x.FirstNotificationId
	}
	return 0
}

type IsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineReq) Reset() {
	*x = IsOnlineReq{}
	mi := &file_realtime_realtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineReq) ProtoMessage() {}

func (x *IsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineReq.ProtoReflect.Descriptor instead.
func (*IsOnlineReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{13}
}

func (x *IsOnlineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type IsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsOnlineResp) Reset() {
	*x = IsOnlineResp{}
	mi := &file_realtime_realtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResp) ProtoMessage() {}

func (x *IsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResp.ProtoReflect.Descriptor instead.
func (*IsOnlineResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{14}
}

func (x *IsOnlineResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type BatchIsOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsOnlineReq) Reset() {
	*x = BatchIsOnlineReq{}
	mi := &file_realtime_realtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsOnlineReq) ProtoMessage() {}

func (x *BatchIsOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsOnlineReq.ProtoReflect.Descriptor instead.
func (*BatchIsOnlineReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{15}
}

func (x *BatchIsOnlineReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchIsOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        map[int64]bool         `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsOnlineResp) Reset() {
	*x = BatchIsOnlineResp{}
	mi := &file_realtime_realtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsOnlineResp) ProtoMessage() {}

func (x *BatchIsOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsOnlineResp.ProtoReflect.Descriptor instead.
func (*BatchIsOnlineResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{16}
}

func (x *BatchIsOnlineResp) GetStatus() map[int64]bool {
	if x != nil {
		return x.Status
	}
	return nil
}

type RegisterDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceReq) Reset() {
	*x = RegisterDeviceReq{}
	mi := &file_realtime_realtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceReq) ProtoMessage() {}

func (x *RegisterDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceReq.ProtoReflect.Descriptor instead.
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterDeviceReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResp) Reset() {
	*x = RegisterDeviceResp{}
	mi := &file_realtime_realtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResp) ProtoMessage() {}

func (x *RegisterDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResp.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{18}
}

type UnregisterDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceReq) Reset() {
	*x = UnregisterDeviceReq{}
	mi := &file_realtime_realtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceReq) ProtoMessage() {}

func (x *UnregisterDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceReq.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceReq) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{19}
}

func (x *UnregisterDeviceReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type UnregisterDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceResp) Reset() {
	*x = UnregisterDeviceResp{}
	mi := &file_realtime_realtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceResp) ProtoMessage() {}

func (x *UnregisterDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_realtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceResp.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceResp) Descriptor() ([]byte, []int) {
	return file_realtime_realtime_proto_rawDescGZIP(), []int{20}
}

var File_realtime_realtime_proto protoreflect.FileDescriptor

const file_realtime_realtime_proto_rawDesc = "" +
	"\n" +
	"\x17realtime/realtime.proto\x12\brealtime\x1a\x13common/common.proto\"\xd6\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x12!\n" +
	"\freference_id\x18\a \x01(\tR\vreferenceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\x96\x01\n" +
	"\x14ListNotificationsReq\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.common.PaginationR\n" +
	"pagination\x12\x17\n" +
	"\x04type\x18\x02 \x01(\x05H\x00R\x04type\x88\x01\x01\x12\x1c\n" +
	"\ais_read\x18\x03 \x01(\bH\x01R\x06isRead\x88\x01\x01B\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_is_read\"\x8d\x01\n" +
	"\x15ListNotificationsResp\x12<\n" +
	"\rnotifications\x18\x01 \x03(\v2\x16.realtime.NotificationR\rnotifications\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.common.PaginationRespR\n" +
	"pagination\"\x13\n" +
	"\x11GetUnreadCountReq\"*\n" +
	"\x12GetUnreadCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"6\n" +
	"\vMarkReadReq\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"\x0e\n" +
	"\fMarkReadResp\"\x10\n" +
	"\x0eMarkAllReadReq\"\x11\n" +
	"\x0fMarkAllReadResp\"@\n" +
	"\x15DeleteNotificationReq\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"\x18\n" +
	"\x16DeleteNotificationResp\"\x97\x01\n" +
	"\x13PushNotificationReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"J\n" +
	"\x14PushNotificationResp\x122\n" +
	"\x15first_notification_id\x18\x01 \x01(\x03R\x13firstNotificationId\"&\n" +
	"\vIsOnlineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"&\n" +
	"\fIsOnlineResp\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"-\n" +
	"\x10BatchIsOnlineReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\x8f\x01\n" +
	"\x11BatchIsOnlineResp\x12?\n" +
	"\x06status\x18\x01 \x03(\v2'.realtime.BatchIsOnlineResp.StatusEntryR\x06status\x1a9\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"b\n" +
	"\x11RegisterDeviceReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x14\n" +
	"\x12RegisterDeviceResp\"2\n" +
	"\x13UnregisterDeviceReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\x16\n" +
	"\x14UnregisterDeviceResp2\x84\x06\n" +
	"\x0fRealtimeService\x12T\n" +
	"\x11ListNotifications\x12\x1e.realtime.ListNotificationsReq\x1a\x1f.realtime.ListNotificationsResp\x12K\n" +
	"\x0eGetUnreadCount\x12\x1b.realtime.GetUnreadCountReq\x1a\x1c.realtime.GetUnreadCountResp\x129\n" +
	"\bMarkRead\x12\x15.realtime.MarkReadReq\x1a\x16.realtime.MarkReadResp\x12B\n" +
	"\vMarkAllRead\x12\x18.realtime.MarkAllReadReq\x1a\x19.realtime.MarkAllReadResp\x12W\n" +
	"\x12DeleteNotification\x12\x1f.realtime.DeleteNotificationReq\x1a .realtime.DeleteNotificationResp\x12Q\n" +
	"\x10PushNotification\x12\x1d.realtime.PushNotificationReq\x1a\x1e.realtime.PushNotificationResp\x129\n" +
	"\bIsOnline\x12\x15.realtime.IsOnlineReq\x1a\x16.realtime.IsOnlineResp\x12H\n" +
	"\rBatchIsOnline\x12\x1a.realtime.BatchIsOnlineReq\x1a\x1b.realtime.BatchIsOnlineResp\x12K\n" +
	"\x0eRegisterDevice\x12\x1b.realtime.RegisterDeviceReq\x1a\x1c.realtime.RegisterDeviceResp\x12Q\n" +
	"\x10UnregisterDevice\x12\x1d.realtime.UnregisterDeviceReq\x1a\x1e.realtime.UnregisterDeviceRespB9Z7github.com/maomeng/aim/app/realtime-service/pb/realtimeb\x06proto3"

var (
	file_realtime_realtime_proto_rawDescOnce sync.Once
	file_realtime_realtime_proto_rawDescData []byte
)

func file_realtime_realtime_proto_rawDescGZIP() []byte {
	file_realtime_realtime_proto_rawDescOnce.Do(func() {
		file_realtime_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_realtime_proto_rawDesc), len(file_realtime_realtime_proto_rawDesc)))
	})
	return file_realtime_realtime_proto_rawDescData
}

var file_realtime_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_realtime_realtime_proto_goTypes = []any{
	(*Notification)(nil),           // 0: realtime.Notification
	(*ListNotificationsReq)(nil),   // 1: realtime.ListNotificationsReq
	(*ListNotificationsResp)(nil),  // 2: realtime.ListNotificationsResp
	(*GetUnreadCountReq)(nil),      // 3: realtime.GetUnreadCountReq
	(*GetUnreadCountResp)(nil),     // 4: realtime.GetUnreadCountResp
	(*MarkReadReq)(nil),            // 5: realtime.MarkReadReq
	(*MarkReadResp)(nil),           // 6: realtime.MarkReadResp
	(*MarkAllReadReq)(nil),         // 7: realtime.MarkAllReadReq
	(*MarkAllReadResp)(nil),        // 8: realtime.MarkAllReadResp
	(*DeleteNotificationReq)(nil),  // 9: realtime.DeleteNotificationReq
	(*DeleteNotificationResp)(nil), // 10: realtime.DeleteNotificationResp
	(*PushNotificationReq)(nil),    // 11: realtime.PushNotificationReq
	(*PushNotificationResp)(nil),   // 12: realtime.PushNotificationResp
	(*IsOnlineReq)(nil),            // 13: realtime.IsOnlineReq
	(*IsOnlineResp)(nil),           // 14: realtime.IsOnlineResp
	(*BatchIsOnlineReq)(nil),       // 15: realtime.BatchIsOnlineReq
	(*BatchIsOnlineResp)(nil),      // 16: realtime.BatchIsOnlineResp
	(*RegisterDeviceReq)(nil),      // 17: realtime.RegisterDeviceReq
	(*RegisterDeviceResp)(nil),     // 18: realtime.RegisterDeviceResp
	(*UnregisterDeviceReq)(nil),    // 19: realtime.UnregisterDeviceReq
	(*UnregisterDeviceResp)(nil),   // 20: realtime.UnregisterDeviceResp
	nil,                            // 21: realtime.BatchIsOnlineResp.StatusEntry
	(*common.Pagination)(nil),      // 22: common.Pagination
	(*common.PaginationResp)(nil),  // 23: common.PaginationResp
}
var file_realtime_realtime_proto_depIdxs = []int32{
	22, // 0: realtime.ListNotificationsReq.pagination:type_name -> common.Pagination
	0,  // 1: realtime.ListNotificationsResp.notifications:type_name -> realtime.Notification
	23, // 2: realtime.ListNotificationsResp.pagination:type_name -> common.PaginationResp
	21, // 3: realtime.BatchIsOnlineResp.status:type_name -> realtime.BatchIsOnlineResp.StatusEntry
	1,  // 4: realtime.RealtimeService.ListNotifications:input_type -> realtime.ListNotificationsReq
	3,  // 5: realtime.RealtimeService.GetUnreadCount:input_type -> realtime.GetUnreadCountReq
	5,  // 6: realtime.RealtimeService.MarkRead:input_type -> realtime.MarkReadReq
	7,  // 7: realtime.RealtimeService.MarkAllRead:input_type -> realtime.MarkAllReadReq
	9,  // 8: realtime.RealtimeService.DeleteNotification:input_type -> realtime.DeleteNotificationReq
	11, // 9: realtime.RealtimeService.PushNotification:input_type -> realtime.PushNotificationReq
	13, // 10: realtime.RealtimeService.IsOnline:input_type -> realtime.IsOnlineReq
	15, // 11: realtime.RealtimeService.BatchIsOnline:input_type -> realtime.BatchIsOnlineReq
	17, // 12: realtime.RealtimeService.RegisterDevice:input_type -> realtime.RegisterDeviceReq
	19, // 13: realtime.RealtimeService.UnregisterDevice:input_type -> realtime.UnregisterDeviceReq
	2,  // 14: realtime.RealtimeService.ListNotifications:output_type -> realtime.ListNotificationsResp
	4,  // 15: realtime.RealtimeService.GetUnreadCount:output_type -> realtime.GetUnreadCountResp
	6,  // 16: realtime.RealtimeService.MarkRead:output_type -> realtime.MarkReadResp
	8,  // 17: realtime.RealtimeService.MarkAllRead:output_type -> realtime.MarkAllReadResp
	10, // 18: realtime.RealtimeService.DeleteNotification:output_type -> realtime.DeleteNotificationResp
	12, // 19: realtime.RealtimeService.PushNotification:output_type -> realtime.PushNotificationResp
	14, // 20: realtime.RealtimeService.IsOnline:output_type -> realtime.IsOnlineResp
	16, // 21: realtime.RealtimeService.BatchIsOnline:output_type -> realtime.BatchIsOnlineResp
	18, // 22: realtime.RealtimeService.RegisterDevice:output_type -> realtime.RegisterDeviceResp
	20, // 23: realtime.RealtimeService.UnregisterDevice:output_type -> realtime.UnregisterDeviceResp
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_realtime_realtime_proto_init() }
func file_realtime_realtime_proto_init() {
	if File_realtime_realtime_proto != nil {
		return
	}
	file_realtime_realtime_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_realtime_proto_rawDesc), len(file_realtime_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_realtime_proto_goTypes,
		DependencyIndexes: file_realtime_realtime_proto_depIdxs,
		MessageInfos:      file_realtime_realtime_proto_msgTypes,
	}.Build()
	File_realtime_realtime_proto = out.File
	file_realtime_realtime_proto_goTypes = nil
	file_realtime_realtime_proto_depIdxs = nil
}
