// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: realtime/realtime.proto

package realtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeService_ListNotifications_FullMethodName  = "/realtime.RealtimeService/ListNotifications"
	RealtimeService_GetUnreadCount_FullMethodName     = "/realtime.RealtimeService/GetUnreadCount"
	RealtimeService_MarkRead_FullMethodName           = "/realtime.RealtimeService/MarkRead"
	RealtimeService_MarkAllRead_FullMethodName        = "/realtime.RealtimeService/MarkAllRead"
	RealtimeService_DeleteNotification_FullMethodName = "/realtime.RealtimeService/DeleteNotification"
	RealtimeService_PushNotification_FullMethodName   = "/realtime.RealtimeService/PushNotification"
	RealtimeService_IsOnline_FullMethodName           = "/realtime.RealtimeService/IsOnline"
	RealtimeService_BatchIsOnline_FullMethodName      = "/realtime.RealtimeService/BatchIsOnline"
	RealtimeService_RegisterDevice_FullMethodName     = "/realtime.RealtimeService/RegisterDevice"
	RealtimeService_UnregisterDevice_FullMethodName   = "/realtime.RealtimeService/UnregisterDevice"
)

// RealtimeServiceClient is the client API for RealtimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeServiceClient interface {
	ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error)
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
	MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadResp, error)
	MarkAllRead(ctx context.Context, in *MarkAllReadReq, opts ...grpc.CallOption) (*MarkAllReadResp, error)
	DeleteNotification(ctx context.Context, in *DeleteNotificationReq, opts ...grpc.CallOption) (*DeleteNotificationResp, error)
	PushNotification(ctx context.Context, in *PushNotificationReq, opts ...grpc.CallOption) (*PushNotificationResp, error)
	IsOnline(ctx context.Context, in *IsOnlineReq, opts ...grpc.CallOption) (*IsOnlineResp, error)
	BatchIsOnline(ctx context.Context, in *BatchIsOnlineReq, opts ...grpc.CallOption) (*BatchIsOnlineResp, error)
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
	UnregisterDevice(ctx context.Context, in *UnregisterDeviceReq, opts ...grpc.CallOption) (*UnregisterDeviceResp, error)
}

type realtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeServiceClient(cc grpc.ClientConnInterface) RealtimeServiceClient {
	return &realtimeServiceClient{cc}
}

func (c *realtimeServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResp)
	err := c.cc.Invoke(ctx, RealtimeService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResp)
	err := c.cc.Invoke(ctx, RealtimeService_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResp)
	err := c.cc.Invoke(ctx, RealtimeService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) MarkAllRead(ctx context.Context, in *MarkAllReadReq, opts ...grpc.CallOption) (*MarkAllReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllReadResp)
	err := c.cc.Invoke(ctx, RealtimeService_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) DeleteNotification(ctx context.Context, in *DeleteNotificationReq, opts ...grpc.CallOption) (*DeleteNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNotificationResp)
	err := c.cc.Invoke(ctx, RealtimeService_DeleteNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) PushNotification(ctx context.Context, in *PushNotificationReq, opts ...grpc.CallOption) (*PushNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushNotificationResp)
	err := c.cc.Invoke(ctx, RealtimeService_PushNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) IsOnline(ctx context.Context, in *IsOnlineReq, opts ...grpc.CallOption) (*IsOnlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsOnlineResp)
	err := c.cc.Invoke(ctx, RealtimeService_IsOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) BatchIsOnline(ctx context.Context, in *BatchIsOnlineReq, opts ...grpc.CallOption) (*BatchIsOnlineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchIsOnlineResp)
	err := c.cc.Invoke(ctx, RealtimeService_BatchIsOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, RealtimeService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeServiceClient) UnregisterDevice(ctx context.Context, in *UnregisterDeviceReq, opts ...grpc.CallOption) (*UnregisterDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterDeviceResp)
	err := c.cc.Invoke(ctx, RealtimeService_UnregisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealtimeServiceServer is the server API for RealtimeService service.
// All implementations must embed UnimplementedRealtimeServiceServer
// for forward compatibility.
type RealtimeServiceServer interface {
	ListNotifications(context.Context, *ListNotificationsReq) (*ListNotificationsResp, error)
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error)
	MarkRead(context.Context, *MarkReadReq) (*MarkReadResp, error)
	MarkAllRead(context.Context, *MarkAllReadReq) (*MarkAllReadResp, error)
	DeleteNotification(context.Context, *DeleteNotificationReq) (*DeleteNotificationResp, error)
	PushNotification(context.Context, *PushNotificationReq) (*PushNotificationResp, error)
	IsOnline(context.Context, *IsOnlineReq) (*IsOnlineResp, error)
	BatchIsOnline(context.Context, *BatchIsOnlineReq) (*BatchIsOnlineResp, error)
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
	UnregisterDevice(context.Context, *UnregisterDeviceReq) (*UnregisterDeviceResp, error)
	mustEmbedUnimplementedRealtimeServiceServer()
}

// UnimplementedRealtimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeServiceServer struct{}

func (UnimplementedRealtimeServiceServer) ListNotifications(context.Context, *ListNotificationsReq) (*ListNotificationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedRealtimeServiceServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedRealtimeServiceServer) MarkRead(context.Context, *MarkReadReq) (*MarkReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedRealtimeServiceServer) MarkAllRead(context.Context, *MarkAllReadReq) (*MarkAllReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedRealtimeServiceServer) DeleteNotification(context.Context, *DeleteNotificationReq) (*DeleteNotificationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNotification not implemented")
}
func (UnimplementedRealtimeServiceServer) PushNotification(context.Context, *PushNotificationReq) (*PushNotificationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PushNotification not implemented")
}
func (UnimplementedRealtimeServiceServer) IsOnline(context.Context, *IsOnlineReq) (*IsOnlineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsOnline not implemented")
}
func (UnimplementedRealtimeServiceServer) BatchIsOnline(context.Context, *BatchIsOnlineReq) (*BatchIsOnlineResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchIsOnline not implemented")
}
func (UnimplementedRealtimeServiceServer) RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedRealtimeServiceServer) UnregisterDevice(context.Context, *UnregisterDeviceReq) (*UnregisterDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterDevice not implemented")
}
func (UnimplementedRealtimeServiceServer) mustEmbedUnimplementedRealtimeServiceServer() {}
func (UnimplementedRealtimeServiceServer) testEmbeddedByValue()                         {}

// UnsafeRealtimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeServiceServer will
// result in compilation errors.
type UnsafeRealtimeServiceServer interface {
	mustEmbedUnimplementedRealtimeServiceServer()
}

func RegisterRealtimeServiceServer(s grpc.ServiceRegistrar, srv RealtimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRealtimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeService_ServiceDesc, srv)
}

func _RealtimeService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).ListNotifications(ctx, req.(*ListNotificationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).MarkRead(ctx, req.(*MarkReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).MarkAllRead(ctx, req.(*MarkAllReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_DeleteNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).DeleteNotification(ctx, req.(*DeleteNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_PushNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).PushNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_PushNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).PushNotification(ctx, req.(*PushNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_IsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).IsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_IsOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).IsOnline(ctx, req.(*IsOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_BatchIsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIsOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).BatchIsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_BatchIsOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).BatchIsOnline(ctx, req.(*BatchIsOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeService_UnregisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeServiceServer).UnregisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeService_UnregisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeServiceServer).UnregisterDevice(ctx, req.(*UnregisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RealtimeService_ServiceDesc is the grpc.ServiceDesc for RealtimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "realtime.RealtimeService",
	HandlerType: (*RealtimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNotifications",
			Handler:    _RealtimeService_ListNotifications_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _RealtimeService_GetUnreadCount_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _RealtimeService_MarkRead_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _RealtimeService_MarkAllRead_Handler,
		},
		{
			MethodName: "DeleteNotification",
			Handler:    _RealtimeService_DeleteNotification_Handler,
		},
		{
			MethodName: "PushNotification",
			Handler:    _RealtimeService_PushNotification_Handler,
		},
		{
			MethodName: "IsOnline",
			Handler:    _RealtimeService_IsOnline_Handler,
		},
		{
			MethodName: "BatchIsOnline",
			Handler:    _RealtimeService_BatchIsOnline_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _RealtimeService_RegisterDevice_Handler,
		},
		{
			MethodName: "UnregisterDevice",
			Handler:    _RealtimeService_UnregisterDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "realtime/realtime.proto",
}
