// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: file.proto

package fileservice

import (
	"context"

	"github.com/maomeng/aim/app/file-service/pb/file"

	"github.com/maomeng/aim/pkg/pb/common"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeleteFilesReq  = file.BatchDeleteFilesReq
	BatchGetFileInfoReq  = file.BatchGetFileInfoReq
	BatchGetFileInfoResp = file.BatchGetFileInfoResp
	ConfirmUploadReq     = file.ConfirmUploadReq
	ConfirmUploadResp    = file.ConfirmUploadResp
	DeleteFileReq        = file.DeleteFileReq
	FileInfo             = file.FileInfo
	GetDownloadURLReq    = file.GetDownloadURLReq
	GetDownloadURLResp   = file.GetDownloadURLResp
	GetFileInfoReq       = file.GetFileInfoReq
	GetFileInfoResp      = file.GetFileInfoResp
	GetUploadURLReq      = file.GetUploadURLReq
	GetUploadURLResp     = file.GetUploadURLResp
	UploadAvatarReq      = file.UploadAvatarReq
	UploadAvatarResp     = file.UploadAvatarResp

	FileService interface {
		GetUploadURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error)
		ConfirmUpload(ctx context.Context, in *ConfirmUploadReq, opts ...grpc.CallOption) (*ConfirmUploadResp, error)
		GetDownloadURL(ctx context.Context, in *GetDownloadURLReq, opts ...grpc.CallOption) (*GetDownloadURLResp, error)
		GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error)
		BatchGetFileInfo(ctx context.Context, in *BatchGetFileInfoReq, opts ...grpc.CallOption) (*BatchGetFileInfoResp, error)
		DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		BatchDeleteFiles(ctx context.Context, in *BatchDeleteFilesReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		UploadAvatar(ctx context.Context, in *UploadAvatarReq, opts ...grpc.CallOption) (*UploadAvatarResp, error)
	}

	defaultFileService struct {
		cli zrpc.Client
	}
)

func NewFileService(cli zrpc.Client) FileService {
	return &defaultFileService{
		cli: cli,
	}
}

func (m *defaultFileService) GetUploadURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetUploadURL(ctx, in, opts...)
}

func (m *defaultFileService) ConfirmUpload(ctx context.Context, in *ConfirmUploadReq, opts ...grpc.CallOption) (*ConfirmUploadResp, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.ConfirmUpload(ctx, in, opts...)
}

func (m *defaultFileService) GetDownloadURL(ctx context.Context, in *GetDownloadURLReq, opts ...grpc.CallOption) (*GetDownloadURLResp, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetDownloadURL(ctx, in, opts...)
}

func (m *defaultFileService) GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.GetFileInfo(ctx, in, opts...)
}

func (m *defaultFileService) BatchGetFileInfo(ctx context.Context, in *BatchGetFileInfoReq, opts ...grpc.CallOption) (*BatchGetFileInfoResp, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.BatchGetFileInfo(ctx, in, opts...)
}

func (m *defaultFileService) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}

func (m *defaultFileService) BatchDeleteFiles(ctx context.Context, in *BatchDeleteFilesReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.BatchDeleteFiles(ctx, in, opts...)
}

func (m *defaultFileService) UploadAvatar(ctx context.Context, in *UploadAvatarReq, opts ...grpc.CallOption) (*UploadAvatarResp, error) {
	client := file.NewFileServiceClient(m.cli.Conn())
	return client.UploadAvatar(ctx, in, opts...)
}
