// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/maomeng/aim/app/message-service/pb/message"
	"github.com/maomeng/aim/pkg/pb/common"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetMessagesReq  = message.BatchGetMessagesReq
	BatchGetMessagesResp = message.BatchGetMessagesResp
	DeleteMessageReq     = message.DeleteMessageReq
	EditMessageReq       = message.EditMessageReq
	GetAroundSeqReq      = message.GetAroundSeqReq
	GetMessageByIDReq    = message.GetMessageByIDReq
	GetMessageByIDResp   = message.GetMessageByIDResp
	GetMessagesReq       = message.GetMessagesReq
	GetMessagesResp      = message.GetMessagesResp
	RecallMessageReq     = message.RecallMessageReq
	SearchMessagesReq    = message.SearchMessagesReq
	SearchMessagesResp   = message.SearchMessagesResp
	SendBotReplyReq      = message.SendBotReplyReq
	SendBotReplyResp     = message.SendBotReplyResp
	SendBroadcastReq     = message.SendBroadcastReq
	SendBroadcastResp    = message.SendBroadcastResp
	SendMessageReq       = message.SendMessageReq
	SendMessageResp      = message.SendMessageResp
	SendSystemMessageReq = message.SendSystemMessageReq
	SyncMessagesReq      = message.SyncMessagesReq
	SyncMessagesResp     = message.SyncMessagesResp

	MessageService interface {
		// ========== Core ==========
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		RecallMessage(ctx context.Context, in *RecallMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		EditMessage(ctx context.Context, in *EditMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		DeleteMessage(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error)
		// ========== Query ==========
		GetMessages(ctx context.Context, in *GetMessagesReq, opts ...grpc.CallOption) (*GetMessagesResp, error)
		SyncMessages(ctx context.Context, in *SyncMessagesReq, opts ...grpc.CallOption) (*SyncMessagesResp, error)
		GetMessageByID(ctx context.Context, in *GetMessageByIDReq, opts ...grpc.CallOption) (*GetMessageByIDResp, error)
		BatchGetMessages(ctx context.Context, in *BatchGetMessagesReq, opts ...grpc.CallOption) (*BatchGetMessagesResp, error)
		GetAroundSeq(ctx context.Context, in *GetAroundSeqReq, opts ...grpc.CallOption) (*GetMessagesResp, error)
		SearchMessages(ctx context.Context, in *SearchMessagesReq, opts ...grpc.CallOption) (*SearchMessagesResp, error)
		// ========== Broadcast ==========
		SendBroadcast(ctx context.Context, in *SendBroadcastReq, opts ...grpc.CallOption) (*SendBroadcastResp, error)
		// ========== Bot Reply (called by bot-service) ==========
		SendBotReply(ctx context.Context, in *SendBotReplyReq, opts ...grpc.CallOption) (*SendBotReplyResp, error)
		SendSystemMessage(ctx context.Context, in *SendSystemMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{cli: cli}
}

func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultMessageService) RecallMessage(ctx context.Context, in *RecallMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.RecallMessage(ctx, in, opts...)
}

func (m *defaultMessageService) EditMessage(ctx context.Context, in *EditMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.EditMessage(ctx, in, opts...)
}

func (m *defaultMessageService) DeleteMessage(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*common.BaseResponse, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.DeleteMessage(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessages(ctx context.Context, in *GetMessagesReq, opts ...grpc.CallOption) (*GetMessagesResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

func (m *defaultMessageService) SyncMessages(ctx context.Context, in *SyncMessagesReq, opts ...grpc.CallOption) (*SyncMessagesResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SyncMessages(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessageByID(ctx context.Context, in *GetMessageByIDReq, opts ...grpc.CallOption) (*GetMessageByIDResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessageByID(ctx, in, opts...)
}

func (m *defaultMessageService) BatchGetMessages(ctx context.Context, in *BatchGetMessagesReq, opts ...grpc.CallOption) (*BatchGetMessagesResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.BatchGetMessages(ctx, in, opts...)
}

func (m *defaultMessageService) GetAroundSeq(ctx context.Context, in *GetAroundSeqReq, opts ...grpc.CallOption) (*GetMessagesResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.GetAroundSeq(ctx, in, opts...)
}

func (m *defaultMessageService) SearchMessages(ctx context.Context, in *SearchMessagesReq, opts ...grpc.CallOption) (*SearchMessagesResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SearchMessages(ctx, in, opts...)
}

func (m *defaultMessageService) SendBroadcast(ctx context.Context, in *SendBroadcastReq, opts ...grpc.CallOption) (*SendBroadcastResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SendBroadcast(ctx, in, opts...)
}

func (m *defaultMessageService) SendBotReply(ctx context.Context, in *SendBotReplyReq, opts ...grpc.CallOption) (*SendBotReplyResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SendBotReply(ctx, in, opts...)
}

func (m *defaultMessageService) SendSystemMessage(ctx context.Context, in *SendSystemMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SendSystemMessage(ctx, in, opts...)
}
