import type { ThemeConfig } from 'antd';

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: '#FB7299',
    colorInfo: '#FB7299',
    colorSuccess: '#73D0A4',
    colorWarning: '#FFB347',
    colorError: '#FF6B8A',
    colorLink: '#FB7299',
    colorLinkHover: '#FC8BAB',
    colorBgBase: '#FEF6F8',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#FEF6F8',
    colorBgSpotlight: '#FFE0E6',
    colorBorder: '#FFE0E6',
    colorBorderSecondary: '#FFE8ED',
    colorText: '#3D2E35',
    colorTextSecondary: '#8A7A81',
    colorTextTertiary: '#C4B4BB',
    colorTextQuaternary: '#E0D0D7',
    colorFill: 'rgba(251,114,153,0.04)',
    colorFillSecondary: 'rgba(251,114,153,0.02)',
    colorFillTertiary: 'rgba(251,114,153,0.01)',
    colorFillQuaternary: 'rgba(251,114,153,0.005)',
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 8,
    fontFamily: "'Satoshi', 'DM Sans', -apple-system, BlinkMacSystemFont, 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: 14,
    lineHeight: 1.6,
    wireframe: false,
  },
  components: {
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: 'rgba(251,114,153,0.1)',
      itemSelectedColor: '#FB7299',
      itemColor: '#8A7A81',
      itemHoverBg: 'rgba(251,114,153,0.06)',
      itemHoverColor: '#3D2E35',
      itemBorderRadius: 8,
      iconSize: 20,
    },
    Button: {
      primaryShadow: '0 4px 16px rgba(251,114,153,0.25)',
      primaryColor: '#FFFFFF',
      defaultBg: '#FFFFFF',
      defaultColor: '#3D2E35',
      defaultBorderColor: '#FFE0E6',
      defaultHoverBg: '#FFF0F3',
      defaultHoverColor: '#FB7299',
      defaultHoverBorderColor: '#FB7299',
    },
    Input: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#FFE0E6',
      activeBorderColor: '#FB7299',
      hoverBorderColor: '#FB7299',
      colorText: '#3D2E35',
      colorTextPlaceholder: '#C4B4BB',
      addonBg: '#FFFFFF',
    },
    Select: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#FFE0E6',
      colorText: '#3D2E35',
      colorTextPlaceholder: '#C4B4BB',
      optionSelectedBg: 'rgba(251,114,153,0.1)',
    },
    Modal: {
      contentBg: '#FFFFFF',
      headerBg: '#FFFFFF',
      footerBg: '#FFFFFF',
      colorText: '#3D2E35',
      colorIcon: '#C4B4BB',
    },
    Drawer: {
      colorBgElevated: '#FFFFFF',
    },
    Tooltip: {
      colorBgSpotlight: '#3D2E35',
      colorText: '#FFFFFF',
    },
    Tabs: {
      itemSelectedColor: '#FB7299',
      inkBarColor: '#FB7299',
      colorText: '#8A7A81',
    },
    Badge: {
      colorError: '#FF6B8A',
    },
    Divider: {
      colorSplit: '#FFE0E6',
    },
    Spin: {
      colorPrimary: '#FB7299',
    },
    Switch: {
      colorPrimary: '#FB7299',
    },
    Checkbox: {
      colorPrimary: '#FB7299',
    },
    Radio: {
      colorPrimary: '#FB7299',
    },
    Table: {
      colorBgContainer: 'transparent',
      borderColor: '#FFE0E6',
      colorText: '#3D2E35',
      colorTextSecondary: '#8A7A81',
      headerBg: '#FFF0F3',
      headerColor: '#8A7A81',
      rowHoverBg: 'rgba(251,114,153,0.06)',
    },
  },
};
