// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.4
// source: ai-bot-service/conversation_tool.proto

package aibot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummarizeReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ConvId int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	UserId int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Range:
	//
	//	*SummarizeReq_LastMessageCount
	//	*SummarizeReq_TimeRange
	//	*SummarizeReq_All
	Range         isSummarizeReq_Range `protobuf_oneof:"range"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeReq) Reset() {
	*x = SummarizeReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeReq) ProtoMessage() {}

func (x *SummarizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeReq.ProtoReflect.Descriptor instead.
func (*SummarizeReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{0}
}

func (x *SummarizeReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *SummarizeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SummarizeReq) GetRange() isSummarizeReq_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *SummarizeReq) GetLastMessageCount() int32 {
	if x != nil {
		if x, ok := x.Range.(*SummarizeReq_LastMessageCount); ok {
			return x.LastMessageCount
		}
	}
	return 0
}

func (x *SummarizeReq) GetTimeRange() *TimeRange {
	if x != nil {
		if x, ok := x.Range.(*SummarizeReq_TimeRange); ok {
			return x.TimeRange
		}
	}
	return nil
}

func (x *SummarizeReq) GetAll() bool {
	if x != nil {
		if x, ok := x.Range.(*SummarizeReq_All); ok {
			return x.All
		}
	}
	return false
}

type isSummarizeReq_Range interface {
	isSummarizeReq_Range()
}

type SummarizeReq_LastMessageCount struct {
	LastMessageCount int32 `protobuf:"varint,3,opt,name=last_message_count,json=lastMessageCount,proto3,oneof"`
}

type SummarizeReq_TimeRange struct {
	TimeRange *TimeRange `protobuf:"bytes,4,opt,name=time_range,json=timeRange,proto3,oneof"`
}

type SummarizeReq_All struct {
	All bool `protobuf:"varint,5,opt,name=all,proto3,oneof"`
}

func (*SummarizeReq_LastMessageCount) isSummarizeReq_Range() {}

func (*SummarizeReq_TimeRange) isSummarizeReq_Range() {}

func (*SummarizeReq_All) isSummarizeReq_Range() {}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeRange) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type SummarizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SummaryId     int64                  `protobuf:"varint,1,opt,name=summary_id,json=summaryId,proto3" json:"summary_id,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Todos         []*TodoItem            `protobuf:"bytes,3,rep,name=todos,proto3" json:"todos,omitempty"`
	TotalMessages int32                  `protobuf:"varint,4,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "processing" | "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResp) Reset() {
	*x = SummarizeResp{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResp) ProtoMessage() {}

func (x *SummarizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResp.ProtoReflect.Descriptor instead.
func (*SummarizeResp) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{2}
}

func (x *SummarizeResp) GetSummaryId() int64 {
	if x != nil {
		return x.SummaryId
	}
	return 0
}

func (x *SummarizeResp) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeResp) GetTodos() []*TodoItem {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *SummarizeResp) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *SummarizeResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SummarizeResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetConvSummariesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConvSummariesReq) Reset() {
	*x = GetConvSummariesReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConvSummariesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvSummariesReq) ProtoMessage() {}

func (x *GetConvSummariesReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvSummariesReq.ProtoReflect.Descriptor instead.
func (*GetConvSummariesReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{3}
}

func (x *GetConvSummariesReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *GetConvSummariesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetConvSummariesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SummarizeResp       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConvSummariesResp) Reset() {
	*x = GetConvSummariesResp{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConvSummariesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvSummariesResp) ProtoMessage() {}

func (x *GetConvSummariesResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvSummariesResp.ProtoReflect.Descriptor instead.
func (*GetConvSummariesResp) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{4}
}

func (x *GetConvSummariesResp) GetItems() []*SummarizeResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateTodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	SummaryId     int64                  `protobuf:"varint,2,opt,name=summary_id,json=summaryId,proto3" json:"summary_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoReq) Reset() {
	*x = CreateTodoReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoReq) ProtoMessage() {}

func (x *CreateTodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoReq.ProtoReflect.Descriptor instead.
func (*CreateTodoReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTodoReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *CreateTodoReq) GetSummaryId() int64 {
	if x != nil {
		return x.SummaryId
	}
	return 0
}

func (x *CreateTodoReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TodoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SummaryId     int64                  `protobuf:"varint,2,opt,name=summary_id,json=summaryId,proto3" json:"summary_id,omitempty"`
	ConvId        int64                  `protobuf:"varint,3,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{6}
}

func (x *TodoItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoItem) GetSummaryId() int64 {
	if x != nil {
		return x.SummaryId
	}
	return 0
}

func (x *TodoItem) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *TodoItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TodoItem) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TodoItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TodoItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UpdateTodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodoId        int64                  `protobuf:"varint,1,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoReq) Reset() {
	*x = UpdateTodoReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoReq) ProtoMessage() {}

func (x *UpdateTodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoReq.ProtoReflect.Descriptor instead.
func (*UpdateTodoReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTodoReq) GetTodoId() int64 {
	if x != nil {
		return x.TodoId
	}
	return 0
}

func (x *UpdateTodoReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateTodoReq) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type DeleteTodoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodoId        int64                  `protobuf:"varint,1,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoReq) Reset() {
	*x = DeleteTodoReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoReq) ProtoMessage() {}

func (x *DeleteTodoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoReq.ProtoReflect.Descriptor instead.
func (*DeleteTodoReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTodoReq) GetTodoId() int64 {
	if x != nil {
		return x.TodoId
	}
	return 0
}

type ReplyCandidatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReplyToMsgId  int64                  `protobuf:"varint,3,opt,name=reply_to_msg_id,json=replyToMsgId,proto3" json:"reply_to_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCandidatesReq) Reset() {
	*x = ReplyCandidatesReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCandidatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCandidatesReq) ProtoMessage() {}

func (x *ReplyCandidatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCandidatesReq.ProtoReflect.Descriptor instead.
func (*ReplyCandidatesReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{9}
}

func (x *ReplyCandidatesReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ReplyCandidatesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplyCandidatesReq) GetReplyToMsgId() int64 {
	if x != nil {
		return x.ReplyToMsgId
	}
	return 0
}

type ReplyCandidatesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []string               `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "processing" | "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCandidatesResp) Reset() {
	*x = ReplyCandidatesResp{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCandidatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCandidatesResp) ProtoMessage() {}

func (x *ReplyCandidatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCandidatesResp.ProtoReflect.Descriptor instead.
func (*ReplyCandidatesResp) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{10}
}

func (x *ReplyCandidatesResp) GetCandidates() []string {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ReplyCandidatesResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TranslateMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	TargetLang    string                 `protobuf:"bytes,2,opt,name=target_lang,json=targetLang,proto3" json:"target_lang,omitempty"`
	MsgId         int64                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateMessageReq) Reset() {
	*x = TranslateMessageReq{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateMessageReq) ProtoMessage() {}

func (x *TranslateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateMessageReq.ProtoReflect.Descriptor instead.
func (*TranslateMessageReq) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{11}
}

func (x *TranslateMessageReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateMessageReq) GetTargetLang() string {
	if x != nil {
		return x.TargetLang
	}
	return ""
}

func (x *TranslateMessageReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type TranslateMessageResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TranslatedText string                 `protobuf:"bytes,1,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"`
	DetectedLang   string                 `protobuf:"bytes,2,opt,name=detected_lang,json=detectedLang,proto3" json:"detected_lang,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "processing" | "completed"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslateMessageResp) Reset() {
	*x = TranslateMessageResp{}
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateMessageResp) ProtoMessage() {}

func (x *TranslateMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_bot_service_conversation_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateMessageResp.ProtoReflect.Descriptor instead.
func (*TranslateMessageResp) Descriptor() ([]byte, []int) {
	return file_ai_bot_service_conversation_tool_proto_rawDescGZIP(), []int{12}
}

func (x *TranslateMessageResp) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *TranslateMessageResp) GetDetectedLang() string {
	if x != nil {
		return x.DetectedLang
	}
	return ""
}

func (x *TranslateMessageResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ai_bot_service_conversation_tool_proto protoreflect.FileDescriptor

const file_ai_bot_service_conversation_tool_proto_rawDesc = "" +
	"\n" +
	"&ai-bot-service/conversation_tool.proto\x12\x05aibot\x1a\x1bgoogle/protobuf/empty.proto\"\xc0\x01\n" +
	"\fSummarizeReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12.\n" +
	"\x12last_message_count\x18\x03 \x01(\x05H\x00R\x10lastMessageCount\x121\n" +
	"\n" +
	"time_range\x18\x04 \x01(\v2\x10.aibot.TimeRangeH\x00R\ttimeRange\x12\x12\n" +
	"\x03all\x18\x05 \x01(\bH\x00R\x03allB\a\n" +
	"\x05range\"E\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\xcd\x01\n" +
	"\rSummarizeResp\x12\x1d\n" +
	"\n" +
	"summary_id\x18\x01 \x01(\x03R\tsummaryId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12%\n" +
	"\x05todos\x18\x03 \x03(\v2\x0f.aibot.TodoItemR\x05todos\x12%\n" +
	"\x0etotal_messages\x18\x04 \x01(\x05R\rtotalMessages\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"D\n" +
	"\x13GetConvSummariesReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"B\n" +
	"\x14GetConvSummariesResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.aibot.SummarizeRespR\x05items\"a\n" +
	"\rCreateTodoReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x1d\n" +
	"\n" +
	"summary_id\x18\x02 \x01(\x03R\tsummaryId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xbe\x01\n" +
	"\bTodoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"summary_id\x18\x02 \x01(\x03R\tsummaryId\x12\x17\n" +
	"\aconv_id\x18\x03 \x01(\x03R\x06convId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"V\n" +
	"\rUpdateTodoReq\x12\x17\n" +
	"\atodo_id\x18\x01 \x01(\x03R\x06todoId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"(\n" +
	"\rDeleteTodoReq\x12\x17\n" +
	"\atodo_id\x18\x01 \x01(\x03R\x06todoId\"m\n" +
	"\x12ReplyCandidatesReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12%\n" +
	"\x0freply_to_msg_id\x18\x03 \x01(\x03R\freplyToMsgId\"M\n" +
	"\x13ReplyCandidatesResp\x12\x1e\n" +
	"\n" +
	"candidates\x18\x01 \x03(\tR\n" +
	"candidates\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"a\n" +
	"\x13TranslateMessageReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vtarget_lang\x18\x02 \x01(\tR\n" +
	"targetLang\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x03R\x05msgId\"|\n" +
	"\x14TranslateMessageResp\x12'\n" +
	"\x0ftranslated_text\x18\x01 \x01(\tR\x0etranslatedText\x12#\n" +
	"\rdetected_lang\x18\x02 \x01(\tR\fdetectedLang\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xf6\x03\n" +
	"\x17ConversationToolService\x12B\n" +
	"\x15SummarizeConversation\x12\x13.aibot.SummarizeReq\x1a\x14.aibot.SummarizeResp\x12K\n" +
	"\x10GetConvSummaries\x12\x1a.aibot.GetConvSummariesReq\x1a\x1b.aibot.GetConvSummariesResp\x123\n" +
	"\n" +
	"CreateTodo\x12\x14.aibot.CreateTodoReq\x1a\x0f.aibot.TodoItem\x12:\n" +
	"\n" +
	"UpdateTodo\x12\x14.aibot.UpdateTodoReq\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"DeleteTodo\x12\x14.aibot.DeleteTodoReq\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x17GenerateReplyCandidates\x12\x19.aibot.ReplyCandidatesReq\x1a\x1a.aibot.ReplyCandidatesResp\x12K\n" +
	"\x10TranslateMessage\x12\x1a.aibot.TranslateMessageReq\x1a\x1b.aibot.TranslateMessageRespB4Z2github.com/maomeng/aim/app/ai-bot-service/pb/aibotb\x06proto3"

var (
	file_ai_bot_service_conversation_tool_proto_rawDescOnce sync.Once
	file_ai_bot_service_conversation_tool_proto_rawDescData []byte
)

func file_ai_bot_service_conversation_tool_proto_rawDescGZIP() []byte {
	file_ai_bot_service_conversation_tool_proto_rawDescOnce.Do(func() {
		file_ai_bot_service_conversation_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_bot_service_conversation_tool_proto_rawDesc), len(file_ai_bot_service_conversation_tool_proto_rawDesc)))
	})
	return file_ai_bot_service_conversation_tool_proto_rawDescData
}

var file_ai_bot_service_conversation_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ai_bot_service_conversation_tool_proto_goTypes = []any{
	(*SummarizeReq)(nil),         // 0: aibot.SummarizeReq
	(*TimeRange)(nil),            // 1: aibot.TimeRange
	(*SummarizeResp)(nil),        // 2: aibot.SummarizeResp
	(*GetConvSummariesReq)(nil),  // 3: aibot.GetConvSummariesReq
	(*GetConvSummariesResp)(nil), // 4: aibot.GetConvSummariesResp
	(*CreateTodoReq)(nil),        // 5: aibot.CreateTodoReq
	(*TodoItem)(nil),             // 6: aibot.TodoItem
	(*UpdateTodoReq)(nil),        // 7: aibot.UpdateTodoReq
	(*DeleteTodoReq)(nil),        // 8: aibot.DeleteTodoReq
	(*ReplyCandidatesReq)(nil),   // 9: aibot.ReplyCandidatesReq
	(*ReplyCandidatesResp)(nil),  // 10: aibot.ReplyCandidatesResp
	(*TranslateMessageReq)(nil),  // 11: aibot.TranslateMessageReq
	(*TranslateMessageResp)(nil), // 12: aibot.TranslateMessageResp
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_ai_bot_service_conversation_tool_proto_depIdxs = []int32{
	1,  // 0: aibot.SummarizeReq.time_range:type_name -> aibot.TimeRange
	6,  // 1: aibot.SummarizeResp.todos:type_name -> aibot.TodoItem
	2,  // 2: aibot.GetConvSummariesResp.items:type_name -> aibot.SummarizeResp
	0,  // 3: aibot.ConversationToolService.SummarizeConversation:input_type -> aibot.SummarizeReq
	3,  // 4: aibot.ConversationToolService.GetConvSummaries:input_type -> aibot.GetConvSummariesReq
	5,  // 5: aibot.ConversationToolService.CreateTodo:input_type -> aibot.CreateTodoReq
	7,  // 6: aibot.ConversationToolService.UpdateTodo:input_type -> aibot.UpdateTodoReq
	8,  // 7: aibot.ConversationToolService.DeleteTodo:input_type -> aibot.DeleteTodoReq
	9,  // 8: aibot.ConversationToolService.GenerateReplyCandidates:input_type -> aibot.ReplyCandidatesReq
	11, // 9: aibot.ConversationToolService.TranslateMessage:input_type -> aibot.TranslateMessageReq
	2,  // 10: aibot.ConversationToolService.SummarizeConversation:output_type -> aibot.SummarizeResp
	4,  // 11: aibot.ConversationToolService.GetConvSummaries:output_type -> aibot.GetConvSummariesResp
	6,  // 12: aibot.ConversationToolService.CreateTodo:output_type -> aibot.TodoItem
	13, // 13: aibot.ConversationToolService.UpdateTodo:output_type -> google.protobuf.Empty
	13, // 14: aibot.ConversationToolService.DeleteTodo:output_type -> google.protobuf.Empty
	10, // 15: aibot.ConversationToolService.GenerateReplyCandidates:output_type -> aibot.ReplyCandidatesResp
	12, // 16: aibot.ConversationToolService.TranslateMessage:output_type -> aibot.TranslateMessageResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ai_bot_service_conversation_tool_proto_init() }
func file_ai_bot_service_conversation_tool_proto_init() {
	if File_ai_bot_service_conversation_tool_proto != nil {
		return
	}
	file_ai_bot_service_conversation_tool_proto_msgTypes[0].OneofWrappers = []any{
		(*SummarizeReq_LastMessageCount)(nil),
		(*SummarizeReq_TimeRange)(nil),
		(*SummarizeReq_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_bot_service_conversation_tool_proto_rawDesc), len(file_ai_bot_service_conversation_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_bot_service_conversation_tool_proto_goTypes,
		DependencyIndexes: file_ai_bot_service_conversation_tool_proto_depIdxs,
		MessageInfos:      file_ai_bot_service_conversation_tool_proto_msgTypes,
	}.Build()
	File_ai_bot_service_conversation_tool_proto = out.File
	file_ai_bot_service_conversation_tool_proto_goTypes = nil
	file_ai_bot_service_conversation_tool_proto_depIdxs = nil
}
